### PR TITLE
Update 2.7.0 release notes

### PR DESCRIPTION
**Pull request by joshmoore**
Got one or two more PRs in. Propose to release as 2.7.0. Anything else anyone wants to add? Objections?

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Josh! 😄

**Comment by joshmoore** [comment]
Gladly. Are you moving forward with the release or more feedback needed? Also note that the 2.6 series didn't auto-generate a release -- https://github.com/zarr-developers/zarr-python/tags

**Comment by jakirkham** [comment]
Yep

Yeah I see that. Do we know why that was?

**Comment by joshmoore** [comment]
I assume something that happened in the GHA migration, but I haven't looked into it.

**Comment by joshmoore** [comment]
Pushing a tag was sufficient to release:

https://pypi.org/project/zarr/2.7.0/

We can figure out the GitHub Releases later, possibly using @Carreau's idea from https://github.com/ipython/ipython/releases of having a final entry to say, "Don't look here!"

**Pull request merged**
