### PR TITLE
Default write empty chunks false

### PR DESCRIPTION
**Pull request by joshmoore**
Re-opening https://github.com/zarr-developers/zarr-python/pull/853 from another branch to see if that fixes the github action jobs.

### CODE REVIEW

**Comment by jakirkham** [comment]
Also trying a no change PR ( https://github.com/zarr-developers/zarr-python/pull/952 ) to see if this is a CI issue

**Comment by joshmoore** [comment]
Fewer are hanging but not nothing. 😵‍💫

**Comment by jakirkham** [comment]
It would be good to get a clearer idea on why that is happening. Did we manage to get a log that we could look at? Waited for a while to see if GH Actions would include output, but nothing showed up.

**Comment by jni** [comment]
@joshmoore @jakirkham this is *very* reminiscent of my own misadventures with `test_sync`, deadlocks, and CI timeouts. @joshmoore want to try your own advice?

https://github.com/zarr-developers/zarr-python/pull/725#issuecomment-853813097

>  Usually slow tests are printed at the end, but if they aren't completing we don't get the list! Can you add pytest -sv to the workflow or add pypi.org/project/pytest-timeout so we can get an idea on what's gone sideways?

This commit adds the timeout:

[`4e7733c` (#725)](https://github.com/zarr-developers/zarr-python/pull/725/commits/4e7733c0f0640c66d223dd769cab6f16ea037961)

**Comment by joshmoore** [comment]
Heh. I think I thought that that was now done everywhere. Pushing a commit with lots of timeouts here now.

**Comment by jakirkham** [comment]
The thing is this hang showed up very recently. It makes me wonder if there is something we changed or a dependency update in the environment that changed, which is causing issues.

For example `fasteners` was updated recently. To save writing this again, please read this comment ( https://github.com/zarr-developers/zarr-python/pull/952#issuecomment-1022793956 ).

**Comment by joshmoore** [comment]
Interesting that not even `timeout` seems to be working here.

**Comment by joshmoore** [comment]
0.16.3 seemes safe, @jakirkham. Trying 0.17.1 here now.

**Comment by joshmoore** [comment]
0.17.1 seems to be hanging on 3.9 != 1.21.0 as well.

**Comment by joshmoore** [comment]
Pushed the commits up to the 0.16.3 pin to #853.

**Comment by jakirkham** [comment]
The fact that timeout doesn't work makes me wonder if the hang is in C. Is it possible this is NumPy related? Is NumPy 1.22 hanging somewhere? What if we pinned to NumPy 1.20 in the jobs currently skipping 1.21?

**Comment by jakirkham** [comment]
Yeah sorry I think you may be right. Going with 0.16 seems like the right idea. There were deadlock issues in previous 0.17 releases it seems

**Comment by joshmoore** [comment]
> Going with 0.16 seems like the right idea.

Yeah, I was feeling pretty good about it until https://github.com/zarr-developers/zarr-python/pull/853/commits/080a854e28bd386fe1bbef9620aba2a83d1a909c timed out again. But perhaps that PR is somehow "tainted".

**Comment by jakirkham** [comment]
Maybe we should run tests with more verbosity? Perhaps that points out which test hangs so we can investigate further

**Comment by jakirkham** [comment]
Power cycling for CI

**Comment by jakirkham** [comment]
Looks like this is going to fail without the NumPy upgrade ( https://github.com/zarr-developers/zarr-python/pull/955 )

**Comment by joshmoore** [comment]
Closing along with https://github.com/zarr-developers/zarr-python/pull/952

Looks like the scare is over.

**Pull request closed without merging**
