### PR TITLE
[V3] Allow for incomplete codec metadata using numcodecs.get_codec

### LINKED ISSUE #1443: Will V3 compressor codecs require all parameters in array metadata?
### Zarr version

v2.14.3

### Numcodecs version

v0.11.0

### Python Version

3.10

### Operating System

Mac

### Installation

pip

### Description

The current V3 implementation seems to require a more specific set of parameters for codecs/compressors than V2 did. The code sample below demonstrates how all configuration parameters are extracted separately:

https://github.com/zarr-developers/zarr-python/blob/b3cafa96b88c362e7843df8e2a07499588b7fa49/zarr/meta.py#L443-L460

Whereas in V2, the compressor parameters were simply passed on to [`numcodecs.get_config`](https://github.com/zarr-developers/numcodecs/blob/4f194b661faf1f945cb21b1ac1f19c4314ff8f05/numcodecs/registry.py#L51C1-L52C1)

https://github.com/zarr-developers/zarr-python/blob/b3cafa96b88c362e7843df8e2a07499588b7fa49/zarr/meta.py#L169-L171

## Question:
Was this an intentional change? If so, I foresee a number of downstream projects that will need to adjust their expectations (e.g. Kerchunk, Tifffile). 

### Steps to reproduce

I ran into this working on a V2->V3 conversion tool for Kerchunk. A minimal example is not available at this time.

xref: https://github.com/cgohlke/tifffile/issues/211

### PR DESCRIPTION
**Pull request by jhamman**
This PR refactors how codecs are instantiated in the current V3 implementation. This allows for default parameters to be omitted.

TODO:
* [x] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

closes #1443

### CODE REVIEW

**Review by rabernat — CHANGES_REQUESTED** [review]
I am in favor of making the handling of codec configuration the same in V2 vs V3.

I do think this needs a test to verify that the situation described in https://github.com/cgohlke/tifffile/issues/211 is handled correctly after this change.

**Comment by jhamman** [comment]
Test failures are unrelated and are fixed here https://github.com/zarr-developers/zarr-python/pull/1450

**Comment by jhamman** [comment]
@zarr-developers/python-core-devs - looking for some final feedback here. If I don't hear any, I'll plan to merge ~7/12.

**Comment by martindurant** [comment]
LGTM. I suppose if the conf has invalid values, you get an exception when the codec is instantiated -  do we have any expectation/test of how that should go?

For the related issue in TIFFfile, I will comment that many codec options, specifically for compressors, are only actually important at compress time, not when reading. It would be useful to know, though, if the defaults in python implementations are compatible with whatever TIFF assumes - I don't know how to do that rigorously.

**Comment by cgohlke** [comment]
> It would be useful to know, though, if the defaults in python implementations are compatible with whatever TIFF assumes - I don't know how to do that rigorously.

The only compression method specified in the TIFF standard that has a codec in the numcodecs package is "deflate". The spec says that "each image segment consists of a single complete zlib data stream.". This is compatible what numcodecs.Zlib handles.

All the other dozens of compression methods found in TIFF are either nowhere specified specifically for TIFF (e.g. LZMA, Zstd) , not supported by numcodecs (PackBits, LZW, CCITT, JPEG), or both (e.g., JPEG2000, WebP, PNG, JetRaw).

The imagecodecs package provides many of those codecs made for TIFF. Few of them might require setting extra arguments, such as JPEG (`jpegtables`), WebP (`hasalpha`), or JetRaw (`shape`). This is handled through tifffile. If not, open an issue there.

**Comment by rabernat** [comment]
@jhamman - we just need release notes for this. That's important, since this change could hypothetically impact existing code.

**Comment by martindurant** [comment]
@cgohlke , thank you for the thorough reply. It seems we have nothing to worry about here.

**Pull request merged**
