### PR TITLE
[WIP] getitems / setitems for BaseStore

### PR DESCRIPTION
**Pull request by d-v-b**
This PR adds `getitems` and `setitems` methods to `BaseStore`, and removes some redundant `hasattr(store, 'getitems')` calls. This makes `FSStore` a bit less special and hopefully would make async array methods a little easier to engineer.

Tests and docs are WIP

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Any chance of getting the codecov back up, @d-v-b ?

**Comment by jakirkham** [comment]
Thanks for working on this Davis! 🙏

We are taking another pass at doing this in PR ( https://github.com/zarr-developers/zarr-python/pull/1131 ). If you have time to look, would welcome your feedback there 🙂

**Comment by jakirkham** [comment]
@madsbk , could you please look over this and see if there are things we need to still include from it since PR ( https://github.com/zarr-developers/zarr-python/pull/1131 ) has been merged?

**Comment by jhamman** [comment]
@d-v-b - what do you think about closing this. The store api is due to change significantly in `v3` so I'm not sure this is worth finishing.

**Comment by d-v-b** [comment]
happy to close!

**Pull request closed without merging**
