### PR TITLE
Pass mode paramter to open_group enabling creation of new ZipStores

### PR DESCRIPTION
**Pull request by hmaarrfk**
The mode parameter was ignored in the case of ZipStores because it wasn't passed along to the normalize function.

Is there a way to add notes to the changelog?

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by Carreau** [comment]
Failure seem to be dues to numpy/setuptools recent changes that break the builds. NOthing related to this code. Maybe just rebasing will be sufficient.

> Is there a way to add notes to the changelog?

As far as I can tell people edit `docs/release.rst` directly.

**Comment by hmaarrfk** [comment]
Master seems updated.

**Comment by joshmoore** [comment]
Hi @hmaarrfk. Sorry that this slipped through the cracks. Do you mind taking a look at the recent changes to the mainline that are causing some conflicts?

**Comment by hmaarrfk** [comment]
No issues. I'll see again when I get some time

**Comment by jhamman** [comment]
I'm going to close this as stale. Folks should feel free to reopen if there is interest in continuing this work.

@hmaarrfk  - I'd also be interested in hearing how you find the ergonomics with ZipStore creation in the v3 branch.

**Comment by hmaarrfk** [comment]
Hmmm. I haven't looked at are in a while. I'll have to revive my efforts. 

Will give you feedback when I have it

**Pull request closed without merging**
