### PR TITLE
Start migrating away from Travis

### PR DESCRIPTION
**Pull request by Carreau**
We are out of travis.ci hours; start migrating to actions.

Not complete; none of the coverage uploading and testing with Mongo or azure is ran here.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Matthias! 😄

**Comment by Carreau** [comment]
> Thanks Matthias! 😄

Thanks; as you can see I'm struggling to make it to work...

**Comment by Carreau** [comment]
Note to self: And it won't trigger a build if I don't commit and push.

**Comment by Carreau** [comment]
the interaction of gh-action and tox is complex, and it seem that they are basically duplicating the same purpose; so I might go without tox.

**Review by jakirkham — APPROVED** [review]

**Comment by Carreau** [comment]
I'm going to rebase and squash.

**Comment by Carreau** [comment]
You can see the delta coverage here:

https://app.codecov.io/gh/zarr-developers/zarr-python/compare/master...no-travis

**Comment by Carreau** [comment]
Ok, that seem to start working; merging as is for now and will refine later.

**Comment by jakirkham** [comment]
Should we try to move off AppVeyor as well? I think GH Actions supports Windows too.

**Pull request merged**
