### PR TITLE
Use ipytree in `.tree` representation

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/zarr-developers/zarr-python/issues/259

Reimplements the `.tree` representation in the Jupyter Notebook using [ipytree]( https://github.com/QuantStack/ipytree ), a Jupyter-widget wrapped jsTree implementation. This is similar to what we had before in that it still uses jsTree under-the-hood. However this is significantly easier for us to maintain and test. Not to mention it works seamlessly in both the legacy notebook and JupyterLab. This does require an extra installation step on the part of the user though. FWIW this was surprisingly quick to implement. 🙂

~~It would be good to reference how users [should install ipytree]( https://github.com/QuantStack/ipytree#installation ). Also still needs a little work to get testing on CI going.~~ That said, this could be handy for a slide or a blogpost while we iron these things out.

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [x] Docs build locally (e.g., run ``tox -e docs``)
* [x] AppVeyor and Travis CI passes
* [x] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by alimanfoo** [comment]
This certainly cleans things up **a lot**! Very nice.

**Comment by jakirkham** [comment]
Yeah it's also much easier to test. We can inspect nodes and see how they relate to each other. Haven't dug into that, but it is definitely an option. 🙂

**Comment by jakirkham** [comment]
Have pushed the notebook with this change for comparison. Can [see with nbviewer]( https://nbviewer.jupyter.org/github/zarr-developers/zarr-python/blob/e7a1a9a2bb1042cf2972965516467aaa32100eba/notebooks/repr_tree.ipynb ).

Different icons don't work as well. So just dropped those examples.

**Comment by alimanfoo** [comment]
Looks very nice :-)

 I'm getting an odd behaviour viewing on my phone, tapping on a node makes
it disappear. Then tapping another node makes the first node reappear, but
the tapped node disappear. Maybe something to do with styling for selected
node. Haven't checked on my laptop yet, don't know if specific to phone.

**Comment by jakirkham** [comment]
Thanks for the feedback. This seems to be caused by selecting the icons in nbviewer. Doesn't happen in the actual Jupyter notebook.

**Comment by jakirkham** [comment]
Have pushed a change that disables all nodes so they cannot be selected. This seems to workaround the issue.

**Comment by jakirkham** [comment]
Here's an [updated link]( https://nbviewer.jupyter.org/github/zarr-developers/zarr-python/blob/11cbdb1e262167a8905c0cea1d879a6ec706a007/notebooks/repr_tree.ipynb ).

**Comment by alimanfoo** [comment]
Cool, thanks John, looks good.

**Comment by jakirkham** [comment]
@alimanfoo, would you have a chance to do a code review?

**Comment by alimanfoo** [comment]
Hi @jakirkham, code looks good to my eye, however looking at the [example notebook](https://nbviewer.jupyter.org/github/zarr-developers/zarr-python/blob/11cbdb1e262167a8905c0cea1d879a6ec706a007/notebooks/repr_tree.ipynb) I don't think the `expand` argument is working correctly, because the trees with `expand=True`, `expand=1`, `expand=2` and `expand=3` all look the same.

**Comment by jakirkham** [comment]
Good catch @alimanfoo! Sorry for the long delay. As with most bugs this was a simple thing 😉

Have rerun on the notebook. Results can be seen [on nbviewer]( https://nbviewer.jupyter.org/github/zarr-developers/zarr-python/blob/45b3ff21c0d12c3913e12899086ab28327ebcf95/notebooks/repr_tree.ipynb ).

**Comment by jakirkham** [comment]
Not sure what is up with Coveralls. Tried messing with it last night and this morning, but it still doesn't seem to be working. Otherwise CI passes.

**Comment by jakirkham** [comment]
Thanks for the review @jrbourbeau! Nothing more from me. Merge away 😀

**Pull request merged**
