### PR TITLE
Fix permissions issue with DirectoryStore

### LINKED ISSUE #325: Set file permissions accoding to umask
Zarr uses temporary files that are moved in place to write meta-files and chunks. As a side effect, the created containers are only readable by the user who created them (as is default for temporary files). A better approach might be to set the file permissions after the move according to the users `umask`.

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR builds on #445 and uses the built-in `open` function for creating temporary files in `DirectoryStore` instead of `tempfile.NamedTemporaryFile`. As outlined in https://github.com/zarr-developers/zarr-python/issues/325#issuecomment-437332397, the reasons for doing this are to avoid the limited permissions associated with `tempfile.NamedTemporaryFile` while also not needing to query current `umask` and then use `chmod`. It's also worth noting that here we're using `uuid` to generate a unique filepath for temporary files that are created. 

Closes #325

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [x] Docs build locally (e.g., run ``tox -e docs``)
* [x] AppVeyor and Travis CI passes
* [x] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jrbourbeau** [comment]
cc @jakirkham @alimanfoo for review when you have a moment

cc @eddienko @d-v-b if possible, could you confirm these changes fix the permissions issues you've encountered recently

**Comment by d-v-b** [comment]
@jrbourbeau some quick tests on my end (creating a container and inspecting permissions) suggests that your changes do indeed fix the problem! Thanks for putting this together.

**Comment by jrbourbeau** [comment]
Awesome, thank you for testing!

**Comment by eddienko** [comment]
Looks good to me as well. I am not sure the test is needed now.

**Comment by jakirkham** [comment]
Thanks @jrbourbeau! Also thanks everyone for testing. 😄

**Comment by alimanfoo** [comment]
Adding my thanks @jrbourbeau and @eddienko, this one has been a real pain point, great to see this go in.

**Pull request merged**
