### PR TITLE
Fix orthogonal indexing with a scalar

### LINKED ISSUE #1931: Regression in 2.18.x with size-1 slicing not resolved
### Zarr version

v2.17.0, 2.18.x

### Numcodecs version

v0.12.1

### Python Version

3.10.0

### Operating System

Linux/Mac

### Installation

Using `pip3` in a venv

### Description

There appears to be a regression from v0.17.x to v0.18.0 that was not resolved in v0.18.1 or v0.18.2 when indexing a zarr array with size-1 dimensions.

### Steps to reproduce

The below works on `zarr==2.17.0`, breaks on `zarr==2.18.1`

```
def min_example():
    import zarr
    import numpy as np

    store = zarr.ZipStore("temp.zip", mode="w")
    arr = zarr.zeros(shape=(100, 200, 10), chunks=(100, 200, 1), compressor=None, store=store, dtype='u1')
    arr[:, :, :] = np.random.randint(0, 255, (100, 200, 10))
    store.close()

    zf = zarr.open("temp.zip", "r")
    print(zf[:, :, 1])
```

### Additional output

The error on 2.18.1 is:

`ValueError: could not broadcast input array from shape (100,200,1) into shape (100,200)`

### PR DESCRIPTION
**Pull request by dcherian**
Fixes #1931 

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by jhamman** [comment]
Thanks @dcherian -- looks good to me. No idea why Appveyor isn't running though.

@zarr-developers/steering-council -- I don't have access to our appveyor account. Seems like another reason to address https://github.com/zarr-developers/zarr-python/issues/1905

**Comment by dcherian** [comment]
OK I'll try and add a hypothesis test for this later.

**Comment by dcherian** [comment]
@jhamman I have reproduced the failure with a hypothesis test now (#1746 ).

Should I point that PR at main or V3?

**Comment by joshmoore** [comment]
> No idea why Appveyor isn't running though.

"AppVeyor was unable to build non-mergeable pull request" -- perhaps it was the change of the default branch?

> @zarr-developers/steering-council -- I don't have access to our appveyor account. Seems like another reason to address #1905

Not sure how I log in either at this point?! (Things look to have changed)

I'd propose we get this and any other regressions out as 2.18.3 (ignoring the job failure).

**Review by dstansby — APPROVED** [review]

**Pull request merged**
