### PR TITLE
Require `setuptools` 64.0.0+

### PR DESCRIPTION
**Pull request by Saransh-cpp**
I completely forgot that `setuptools` introduced editable installs in `v64.0.0`. This means that the installation will fail if a developer, who has `setuptools` < `v64.0.0` installed locally, tries to install `Zarr` with `pip install -e .` right now.

With this PR, the local version of `setuptools` will be automatically updated to the compatible version.

For more information see this tweet - https://twitter.com/juanluisback/status/1557734536586625025?t=rzVtT-91AwzSOvBHanCJ9g&s=19

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by MSanKeys963** [comment]
CC: @joshmoore

**Comment by jakirkham** [comment]
Thanks Saransh! 🙏

Updated the PR title to make this a bit clearer (hope that is ok 🙂)

**Review by jakirkham — APPROVED** [review]

**Comment by joshmoore** [comment]
Finally catching up with my email backlog, I'd like to add a request for help with keeping the release.rst entries up-to-date for PRs. It makes releases *SO* much easier.

**Comment by Saransh-cpp** [comment]
I will update `release.rst` with my PRs.

It might also be nice to add an action that labels every PR with something like "needs changelog" if `release.rst` is not edited. The label would be removed as soon as the PR edits `release.rst`. This would ensure that the PRs are not merged before updating `release.rst`.

**Comment by joshmoore** [comment]
@Saransh-cpp, definitely! Several of the ongoing tasks around `rever` and similar (e.g. https://github.com/zarr-developers/zarr-python/issues/829) are for moving us closer to a simplification of the changelog, but until something like that is in place: I can use the help! :)

**Pull request merged**
