### PR TITLE
Fix structured arrays that contain objects #806

### PR DESCRIPTION
**Pull request by abergou**
* Ensures that the fill value of structured arrays that contain objects
  is encoded using object_codec.

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Hi @abergou. Thanks for the PR! I've kicked off the github actions. 

It looks like this may be a more complete version of https://github.com/zarr-developers/zarr-python/pull/702. Do you mind taking a look and seeing what you think?

**Comment by abergou** [comment]
Sure! Thanks! will take a look tomorrow morning hopefully that's quick enough.

**Comment by joshmoore** [comment]
> hopefully that's quick enough.

Definitely! Cheers.

**Comment by abergou** [comment]
Thanks @joshmoore! Indeed this pull request is a more complete version of #702 . The latter fixes part of the problem, but the fill_value still needs to be encoded by the object_codec to fix the issue for structured arrays.

**Comment by abergou** [comment]
The last patch fixes up some failing unit tests; the remaining unit test failures are not due to this patch. They also appear against the master branch.

**Comment by joshmoore** [comment]
Failures were due to https://github.com/dask/s3fs/issues/513 ; ready for retesting with https://github.com/zarr-developers/zarr-python/pull/812 merged.

**Comment by abergou** [comment]
@joshmoore there is a linting error that is due to this pr; it's purely cosmetic though (i.e. it's an error condition that will not show up unless encode_fill_value/decode_fill_value are called directly), but I'll quickly get together a fix.

**Comment by joshmoore** [comment]
Pushed an attempted codecov fix. Feel free to adapt.

**Comment by joshmoore** [comment]
Green! Is there anyone familiar with object codec'ing that would like to take a look at this?

**Comment by joshmoore** [comment]
Didn't receive any objections over the weekend. Releasing.

**Pull request merged**
