### PR TITLE
Clean up getting started page

### PR DESCRIPTION
**Pull request by dstansby**
The existing getting started page was mostly not-getting-started-content, so I've:

- Move information about the project to a new "about" page
- Moved project highlights to the home page
- Moved the installation page into the getting started page

Open to feedback/suggestions! Will leave as draft for now until I put in a redirect for the installation page (which depends on infastructure in https://github.com/zarr-developers/zarr-python/pull/2555)

### CODE REVIEW

**Comment by d-v-b** [comment]
let me know if this is out of scope, but can we get rid of this "sprinting person" icon, it makes me think we are directing people to an emergency exit: 
image

**Comment by dstansby** [comment]
> can we get rid of this "sprinting person" icon

👍 - I'll take a look for another icon!

**Comment by d-v-b** [comment]
I wonder if all of the "getting started" content should be on the main page? our main page is just links right now, which to me is a missed opportunity -- people should see content there, not just links. As a template, we could copy [pydantic's docs page](https://docs.pydantic.dev/latest/). Once you get past the promotion of their paid logging service (something we will not emulate) they have a bullet-pointed list explaining what pydantic is for, and then some code examples. I think a comparable structure would be much better than our current landing page.

**Comment by dstansby** [comment]
> can we get rid of this "sprinting person" icon

Actually, can I say this is out of scope for this PR? If you open an issue I can do it later though.

**Comment by d-v-b** [comment]
> > can we get rid of this "sprinting person" icon
> 
> Actually, can I say this is out of scope for this PR? If you open an issue I can do it later though.

yes you can say that :) I will open an issue

**Comment by jhamman** [comment]
@dstansby - Unfortunately, I've also edited the getting started section in #2568. In fact, I reworked the getting started section into a proper quick-start. How do you want to resolve the pending conflict?

**Comment by dstansby** [comment]
I'm pro this one being reviewed first since it was opened first, and is much smaller and therefore hopefully easier to review.

**Comment by jhamman** [comment]
@dstansby - I ended up pulling your changes from this PR into my larger docs branch. We discussed at the dev meeting today to collect things there for a few days. Feel free to push/suggest edits to that branch if you like.

**Comment by dstansby** [comment]
Okay great - should we close this then?

**Pull request closed without merging**
