### PR TITLE
Test coverage CI

### PR DESCRIPTION
**Pull request by jrbourbeau**
To see if we're below 100% on `master`

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] Docs build locally (e.g., run ``tox -e docs``)
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
If you look at the Coveralls report, it lists files a few times. Some of these note 100% and some don't. Though the ones that don't typically have lines intentionally excluded (workarounds for old Python or NumPy versions). The cumulative result is 100% coverage. However it is curious that Coveralls no longer reports this correctly. I'm guessing they changed something, which is making cumulative coverage not work correctly. Not sure how though. Maybe this helps give you some context. 🙂

**Comment by jakirkham** [comment]
This seems interesting.

```
Coverage.py warning: Couldn't read data from '/home/travis/build/zarr-developers/zarr-python/.coverage.travis-job-b9c4d5f1-3db6-48d9-b9c7-def15fa379e3.4893.462486': CoverageException: Doesn't seem to be a coverage.py data file
Coverage.py warning: Couldn't read data from '/home/travis/build/zarr-developers/zarr-python/.coverage.travis-job-b9c4d5f1-3db6-48d9-b9c7-def15fa379e3.4894.722251': CoverageException: Doesn't seem to be a coverage.py data file
```

ref: https://travis-ci.org/zarr-developers/zarr-python/jobs/610469624#L2314-L2315

**Comment by jrbourbeau** [comment]
Thanks for the extra info, that does help provide more context. Mostly, I was surprised to see over in https://github.com/zarr-developers/zarr-python/pull/503 two lines ([here](https://coveralls.io/builds/26916306/source?filename=zarr%2Findexing.py#L695) and [here](https://coveralls.io/builds/26916306/source?filename=zarr%2Futil.py#L558)) which are seemingly unrelated to the changes in the PR become uncovered

**Comment by jakirkham** [comment]
Yeah we might want to come up with a special coverage selector for NumPy version similar to what has been done with Python previously.

https://github.com/zarr-developers/zarr-python/blob/c647de1a2468948d16e75086160ce4ac41e9d5f8/tox.ini#L14-L15

https://github.com/zarr-developers/zarr-python/blob/c647de1a2468948d16e75086160ce4ac41e9d5f8/.coveragerc#L7

**Comment by jakirkham** [comment]
Toggling for CI

**Comment by jakirkham** [comment]
Toggling for CI.

**Comment by mzjp2** [comment]
For some reason, coveralls just isn't being communicated with, but I can't tell why. Our `.travis.yml` is the same as always 🤷‍♂

**Comment by jakirkham** [comment]
FWIW after poking at this problem occasionally over the past few months, I'm about as confused as you are.

Maybe we need to use [the `travis-pro` configuration]( https://docs.coveralls.io/supported-ci-services )?

**Comment by mzjp2** [comment]
Just FYI, I've removed the continuous-integration/travis-ci status check and enabled the other other one, based off it being depracated: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by mzjp2** [comment]
Other people with the same problem: https://github.com/lemurheavy/coveralls-public/issues/1408

**Comment by jakirkham** [comment]
Some work to fix Coveralls in PR ( https://github.com/zarr-developers/zarr-python/pull/541 ).

**Comment by jrbourbeau** [comment]
Closing this PR in favor of #541. Thanks for working on this @mzjp2!

**Pull request closed without merging**
