### PR TITLE
Minor doc fix

### PR DESCRIPTION
**Pull request by madsbk**
Minor doc fix, the `.. versionadded::` directive needs surrounding newlines.

cc. @jakirkham 

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thank Mads! 😄

**Comment by joshmoore** [comment]
Indeed! Note this also went in at https://github.com/zarr-developers/zarr-python/pull/853/commits/422beaa9bb9aa5cc307560a2bdf93369d8beeee2

**Comment by jakirkham** [comment]
Oh weird. Wonder why this was still showing up in `master` then?

**Comment by joshmoore** [comment]
Sorry, "went in" was poorly written. "Was also in an open PR"

**Comment by jakirkham** [comment]
Ah ok. Thanks for the clarification!

**Pull request merged**
