### PR TITLE
blocks_to_decompress not used in read_part function

### PR DESCRIPTION
**Pull request by boazmohar**
Unused variable, as indicated by [lgtm.com](https://lgtm.com/projects/g/zarr-developers/zarr-python/snapshot/9546f2312c02be3e91a4a67c8631e21bbb9c73e9/files/zarr/util.py?sort=name&dir=ASC&mode=heatmap#xcd2184c787afdbd8:1)

TODO:
* [x] Add unit tests and/or doctests in docstrings (all tests passed locally)
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
@andrewfulton9, could you please review?

**Comment by andrewfulton9** [comment]
This PR looks good to me. I must have forgot to delete that code when I changed how the blocks where looped through. 

> Interesting. This is perhaps another piece in the puzzle to [#859 (comment)](https://github.com/zarr-developers/zarr-python/pull/859#issuecomment-951255132)
 
I don't think so. I'm sure that `self.nblocks` did not always equal 1 when the partial read capability was added. I'll take a look.

**Comment by joshmoore** [comment]
Thanks @boazmohar and @andrewfulton9 for the review!

**Comment by joshmoore** [comment]
released on the 2.10 line: https://zarr.readthedocs.io/en/stable/release.html#release-2-10-3

**Pull request merged**
