### PR TITLE
Workflow to label PRs with "needs release notes"

### PR DESCRIPTION
**Pull request by Saransh-cpp**
See https://github.com/zarr-developers/zarr-python/pull/1193#issuecomment-1298824828

This will -
- label a PR with "needs release notes" if `docs/release.rst` has not been edited
- remove the label as soon as `docs/release.rst` is edited

A working demo - https://github.com/Saransh-cpp/zarr-python/pull/1

This will encourage (or maybe require, depending on the maintainers) developers to update `release.rst` with every PR! 

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Interesting! This seems useful. Thanks Saransh 🙏 

Wonder how this looks if we change the release note process to use release fragments ( https://github.com/zarr-developers/zarr-python/issues/829 )?

**Comment by joshmoore** [comment]
My guess would be: `- any: ['!.release-notes/*']` (or similar) would work, saying "you must have added a file under this directory.

**Comment by Saransh-cpp** [comment]
> \- any: ['!.release-notes/*']

Yes, this should work according to the examples listed in their README.

**Comment by jakirkham** [comment]
Could you please send a PR to add this to Numcodecs too?

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Saransh! 🙏 Merging when CI passes

**Comment by jakirkham** [comment]
(needed a release note 😉)

**Comment by Saransh-cpp** [comment]
Haha, missed that!

**Comment by joshmoore** [comment]
>> (needed a release note 😉)
> Haha, missed that!

🤣

**Pull request merged**
