### PR TITLE
`mktemp()` is deprecated, use `mkstemp()` instead

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Although it was used in tests and examples, therefore with no related security issues as far as I can see, `mktemp()` is deprecated:
https://docs.python.org/3/library/tempfile.html#deprecated-functions-and-variables

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
@DimitriPapadopoulos, looks like this has led to:

```
ERROR zarr/tests/test_storage.py::TestFSStore::test_s3 - AttributeError: modu...
ERROR zarr/tests/test_storage.py::TestFSStore::test_s3_complex - AttributeErr...
ERROR zarr/tests/test_storage.py::TestN5FSStore::test_s3 - AttributeError: mo...
ERROR zarr/tests/test_storage.py::TestN5FSStore::test_s3_complex - AttributeE...
= 181 failed, 2446 passed, 58 skipped, 8 xfailed, 1 xpassed, 18 warnings, 4 errors in 228.41s (0:03:48) =
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/zarr-env/lib/python3.7/shutil.py", line 485, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/share/miniconda/envs/zarr-env/lib/python3.7/shutil.py", line 404, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/usr/share/miniconda/envs/zarr-env/lib/python3.7/shutil.py", line 400, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
NotADirectoryError: [Errno 20] Not a directory: '/tmp/tmprwq45_jf'
```

**Comment by DimitriPapadopoulos** [comment]
Yes, it has to do with the `atexit` handler in tests. I'll look into it.

**Comment by DimitriPapadopoulos** [comment]
It might mean changing the logic of the tests. Because `mktemp()` is used only in tests, it's probably not worth spending time on this issue.

**Comment by joshmoore** [comment]
Understood, @DimitriPapadopoulos. What do you propose to do with this PR?

**Comment by DimitriPapadopoulos** [comment]
Although `mktemp()` is deprecated, I doubt it will be removed any time soon. Let's keep these tests as they are for now.

If you need switching from `mktemp()` to `mkstemp()` in the future, I recommend looking into the management of the lifetime of temporary files, currently handled with [`atexit`](https://docs.python.org/3/library/atexit.html). It could benefit from a switch to [`with ... as`](https://www.python.org/dev/peps/pep-0343/) and/or [`tempfile.TemporaryFile`](https://docs.python.org/3/library/tempfile.html).

I suggest closing this ticket for now.

**Pull request closed without merging**
