### PR TITLE
Add require_parent and check_exists as options 

### PR DESCRIPTION
**Pull request by Cedric-LG**
Add require_parent and check_exists as options when creating an array

This option allows the user to skip the test that check whether the parent group of an array already exists and whether the array or group itself already exist. Based on Issue #460 #

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] Docs build locally (e.g., run ``tox -e docs``)
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @Cedric-LG, just to say the PR looks great, I'll look at adding some tests.

**Comment by alimanfoo** [comment]
Just to refresh here, I still think this would be a useful change, just needs some tests.

**Comment by blackpandan** [comment]
hello is anyone still working on this issue

**Comment by joshmoore** [comment]
Hi @blackpandan. Let's see if we hear anything from @Cedric-LG, but even if we do, your help in rebasing this PR to fix the conflicting files would already be _wonderful_! If you decide to work on that, feel free to open a new PR with any work.

**Comment by jhamman** [comment]
I'm going to close this as stale. Folks should feel free to reopen if there is interest in continuing this work.

**Pull request closed without merging**
