### PR TITLE
Move fixtures to `tests`

### PR DESCRIPTION
**Pull request by d-v-b**
Move static fixtures from `fixture` to `tests/fixture`, and alter the corresponding tests to look for fixtures in the new location. These tests contained code for regenerating these fixtures if they were not found; I removed this code, because the fixtures are guaranteed to exist. 

I think generating fixtures at testing time is better than using static files, but the changes here were easier to make. Down the road we can deprecate the static fixtures in a separate PR.

Also, this diff is extremely unwieldy because of the large number of objects in the fixtures directory. Do we really need thousands of files here? Here are the test files modified by this PR:

- https://github.com/d-v-b/zarr-python/blob/00b9b8aa5f2a5fecc278fe8fecb104105a44c061/tests/v2/test_attrs.py#L38
- https://github.com/d-v-b/zarr-python/blob/00b9b8aa5f2a5fecc278fe8fecb104105a44c061/tests/v2/test_dim_separator.py#L42
- https://github.com/d-v-b/zarr-python/blob/array_fixture_fix/tests/v2/conftest.py

Addresses #1812 

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by d-v-b** [comment]
note that tests are passing, but pre-commit and appveyor are not, presumably because there are too many files, leading to timeouts.

**Comment by d-v-b** [comment]
an alternative is to revisit #138 and make these arrays smaller before merging

**Comment by d-v-b** [comment]
I think this is basically finished. A summary of the changes:
- Since the static fixtures are only used by the v2 tests, I moved them all to `tests/v2/fixture`
- There's a large number of static array fixtures that exist only to check that the array can be ready by a future version of zarr. This test is quetionably designed, because if the fixture files are not found, they are programmatically generated at test time, which undermines the premise of the test. Nonetheless, _I kept these tests but reduced the number of chunks in each fixture array to 2_, which keeps the number of checked in files low. 
- There are three tests that refer to static fixtures, but do not really need to -- one test checks whether a group can be created with the name "meta", and another test checks whether unicode strings can be written to attributes, and the last are checking dimension separator stuff. The first two now use the tmpdir fixture instead of static data, the latter uses static fixtures in the new `tests/v2/fixture` directory, but even that test could be done with a vanilla `tmpdir` fixture. 
 
The diff is unreadable. I bundled the changes to the test code into a [single commit](https://github.com/zarr-developers/zarr-python/pull/1813/commits/3b2d1ec0ec1cacf3b742c126ac3d86fc29455c64) to make this more reviewable. That's what reviewers should look at.

**Comment by d-v-b** [comment]
In a separate effort, I just checked auto-generated fixture files by mistake again :face_exhaling: can we get some eyes on this PR so we can fix this behavior.

**Review by normanrz — APPROVED** [review]

**Pull request merged**
