### PR TITLE
add ruff and black to precommit

### PR DESCRIPTION
**Pull request by d-v-b**
Second attempt to add ruff and black to precommit, this time with a non-cursed git history. Supersedes #1321. 

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by d-v-b** [comment]
Any objections to getting this in sooner rather than later? Every change to `main` that doesn't comply with the code formatting contained in this PR generates a merge conflict.

**Comment by joshmoore** [comment]
> Any objections to getting this in sooner rather than later? Every change to main that doesn't comply with the code formatting contained in this PR generates a merge conflict.

Yes. https://github.com/zarr-developers/zarr-python/pull/1305#issuecomment-1384246517 Or rather, what's the plan on updating the existing PRs?

**Comment by d-v-b** [comment]
> Yes. https://github.com/zarr-developers/zarr-python/pull/1305#issuecomment-1384246517 Or rather, what's the plan on updating the existing PRs?

Which PRs do you mean (which are the sharding PRs, and which are the "existing PRs")? In the case of sharding, is there more coming in besides https://github.com/zarr-developers/zarr-python/pull/1096, which this PR builds on?

**Comment by joshmoore** [comment]
https://github.com/zarr-developers/zarr-python/pull/1111 is the other open sharding PR which has now been re-written a couple of times. Existing PRs are just all the other open ones. But if I exclude yours and only look at the last year, that's 23:

https://github.com/zarr-developers/zarr-python/pulls?q=is%3Apr+is%3Aopen++created%3A%3E%3D2022-01-20++-author%3Ad-v-b

**Comment by d-v-b** [comment]
I'm fine with updating this PR every time something new is added to `main`, as long as I'm not doing that indefinitely :)

**Comment by joshmoore** [comment]
I wonder if this would help you, @d-v-b: https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

:smile:

**Comment by d-v-b** [comment]
closing in favor of #1457

**Pull request closed without merging**
