### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by joshmoore**
see:
 - https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
 - https://github.com/zarr-developers/zarr-python/pull/909#issuecomment-1240363698

[Description of PR]

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Primary TODO is convert:

```
from tempfile import mktemp

def write_results(results):
    filename = mktemp()
    with open(filename, "w+") as f:
        f.write(results)
    print("Results written to", filename)
```

to

```
from tempfile import NamedTemporaryFile

def write_results(results):
    with NamedTemporaryFile(mode="w+", delete=False) as f:
        f.write(results)
    print("Results written to", f.name)
```

**Comment by DimitriPapadopoulos** [comment]
CodeQL fails on the very issue documented in https://github.com/zarr-developers/zarr-python/pull/906.

Should we shut up this warning, if possible at all?

**Comment by joshmoore** [comment]
Have you seen how to do that configuration? If not, perhaps it's time to tackle #906.

**Comment by DimitriPapadopoulos** [comment]
See [Dismissing alerts](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing--alerts):
> There are two ways of closing an alert. You can fix the problem in the code, or you can dismiss the alert.
> 
> Dismissing an alert is a way of closing an alert that you don't think needs to be fixed. For example, an error in code that's used only for testing, or when the effort of fixing the error is greater than the potential benefit of improving the code. You can dismiss alerts from code scanning annotations in code, or from the summary list within the **Security** tab.

It looks like we cannot easily dismiss the alerts from a configuration file or from a comment in the line of code that generates the alert.

**Comment by joshmoore** [comment]
@DimitriPapadopoulos, that seems to have done it.

**Comment by joshmoore** [comment]
Green after a restart. Let's merge and see if it helps or hinders. (We can always disable)

**Pull request merged**
