### PR TITLE
Allow to update array fill_values

### LINKED ISSUE #662: Modify fill_value on existing arrays
There is currently no way to chance the fill_value on an existing array (without hacking the metadata). We allow existing arrays to be resized. Why not allow to change the fill_value?

### PR DESCRIPTION
**Pull request by Carreau**
closes #662

### CODE REVIEW

**Comment by joshmoore** [comment]
Closing and re-opening to move from travis to GHA.

**Comment by rabernat** [comment]
Thanks for keeping this alive! It's a small but valuable feature request.

**Comment by joshmoore** [comment]
Fixed a minor issue in the test. Let's see if it goes green.

**Comment by joshmoore** [comment]
@rabernat : Green. You want to do the review honors then?

**Comment by joshmoore** [comment]
Rebased and solved merge conflicts.

**Review by joshmoore — APPROVED** [review]
With 2.11 being in something of a "let's get stuff in" state, I'd say let's get this in.

**Pull request merged**
