### PR TITLE
Update release.rst

### PR DESCRIPTION
**Pull request by MSanKeys963**
Hi all. 👋🏻 

This PR updates the [release.rst](https://github.com/zarr-developers/zarr-python/blob/main/docs/release.rst) to the latest version. 

Please note that I have not updated it under a new release, i.e. **2.16.2**. If we plan to go with **2.16.2** with current updates, I'm happy to modify the `release.rst` accordingly.

Please review. Thanks!

TODO:
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Review by jhamman — APPROVED** [review]

**Comment by joshmoore** [comment]
I'm unclear when the user warnings and the moto failures started showing up, but things have look to be going green now. I'll sign off for now in case anyone wants to release, otherwise I'll take care of it tomorrow (assuming no objections).

**Comment by joshmoore** [comment]
I have not seen a passing Windows/3.9 build in some time:

```
ERROR zarr/tests/test_storage_v3.py::TestFSStoreV3::test_s3_complex - OSError: [Errno 5] Internal Server Error
```

I'm inclined to disable that item in the matrix.

**Comment by joshmoore** [comment]
Finally! It's green. Very *inclined* to get 2.17.0 ASAP.

**Comment by MSanKeys963** [comment]
Thanks a ton, @joshmoore! 🙏🏻

**Pull request merged**
