### PR TITLE
Update TEAM.md

### PR DESCRIPTION
**Pull request by jhamman**
Welcoming @dstansby to the Zarr-Python core dev team! 

cc @zarr-developers/python-core-devs

### CODE REVIEW

**Comment by rabernat** [comment]
Let's make a tweet about this from the Zarr account.

**Comment by MSanKeys963** [comment]
Welcome to the team, @dstansby!

> Let's make a tweet about this from the Zarr account.

Sure. I'll wait until @dstansby accepts the team invite and this PR is merged before sending out the tweet.

**Comment by dstansby** [comment]
🙌 thanks for the invitation, looking forward to working with everyone!

**Review by dstansby — APPROVED** [review]

**Comment by MSanKeys963** [comment]
Tweet: https://x.com/zarr_dev/status/1823037542347719130

**Pull request merged**
