### PR TITLE
fix: add mypy to test dependencies

### LINKED ISSUE #1788: [V3] mypy not running properly in CI
I'm seeing the following output in CI in the v3 branch, under the `run mypy` stage:
```
Run hatch run test:run-mypy
─────────────────────────── test.py3.10-1.24-minimal ───────────────────────────
/bin/sh: 1: mypy: not found
Error: Process completed with exit code 127.
```

Nonetheless, GHA reports this stage as succeeding :upside_down_face: Maybe because 127 is not one of the exit codes it considers a failure. However I think we can consider this test a failure. How should we fix this?

cc @dstansby

### PR DESCRIPTION
**Pull request by d-v-b**
mypy was not in our dev dependencies. this PR adds it. expect CI to fail as mypy actually does something, instead of silently erroring out.

closes #1788 

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by dstansby** [comment]
Since `mypy` runs as part of `pre-commit` anyway, how about just getting rid of the GitHub actions mypy stage?

**Comment by d-v-b** [comment]
> Since mypy runs as part of pre-commit anyway, how about just getting rid of the GitHub actions mypy stage?

We don't run pre-commit as part of CI (and I don't think we necessarily want to) so I do think it makes sense to have mypy as a stage, but I'm open to other opinions here. I am noticing that even with mypy running and reporting errors, CI is still green :thinking:

**Comment by dstansby** [comment]
I suspect https://github.com/zarr-developers/zarr-python/blob/3a9d968dd856efdb3d56cd73ad527baac6ffeded/.github/workflows/test-v3.yml#L41 might be the culprit 😄

**Comment by Saransh-cpp** [comment]
pre-commit is running in the CI (as seen in this PR, but maybe only on PRs? pre-commit.ci is faster than GH Actions so it should be preferred if there are no blockers) - 

image

**Comment by d-v-b** [comment]
> pre-commit is running in the CI (as seen in this PR, but maybe only on PRs? pre-commit.ci is faster than GH Actions so it should be preferred if there are no blockers) -
> image

I stand corrected! in this case, i'm confused that mypy is failing (silently) in GHA, but passing in pre-commit

**Comment by dstansby** [comment]
It's because `types-redis` is installed as part of the pre-commit checks, but not installed on GitHub actions. I think it makes a bit more sense to run `mypy` on the pre-commit check, to avoid duplicating config between the pre-commit config and GitHub actions setup. Alternatively, in GitHub actions `pre-commit run mypy` could be run to make sure the environment is the same as the one developers will see when they run `pre-commit`, but this is kind of what pre-commit.ci is set up to do anyway.

**Comment by d-v-b** [comment]
I'm open to either running mypy in pre-commit or as a stage in CI, but it doesn't seem like we need to run it in both places. It looks like @dstansby and @Saransh-cpp recommend the pre-commit approach; does anyone disagree with this, or otherwise object to removing the mypy stage from CI?

**Comment by jhamman** [comment]
I've found running mypy in pre-commit to be a bit hard to manage -- mostly because we only execute mypy for one Python version. Perhaps there are ways to make sure we have mypy coverage across our matrix of supported Python versions?

**Comment by d-v-b** [comment]
Does the version of python mypy is running on matter? I thought mypy was configured to type-check against a specific python version in [`pyproject.toml`](https://github.com/zarr-developers/zarr-python/blob/ce6fcbbee24f4429a740963cec8b239a0b76cd34/pyproject.toml#L151)

**Comment by dstansby** [comment]
Since `mypy` is a static type checker I don't think it matters which version of Python you run it with, and the results shouldn't depend on that version.

**Review by jhamman — APPROVED** [review]

**Pull request merged**
