### PR TITLE
Fix indexing for scalar numpy values (#967)

### LINKED ISSUE #967: Change in indexing behaviour with numpy ints
After https://github.com/zarr-developers/zarr-python/commit/7c31f041ca8baab860564d9c6332c52f19777e80 there was a breaking change to indexing behavior when a numpy integer type is passed:

For the following array:
```python
z = zarr.group()
a = z.create_dataset("test",shape=(10,))
a[:]=range(10)
```
Before this commit:
`a[np.int64(1)]` has the value `1.0`
After:
`a[np.int64(1)]` has the value `[1.]`

For both cases `a[1]` stays as `1.0` as expected. Was this change expected? This happens a lot when iterating over one numpy array and indexing with it as the iterable is of the numpy type. The fix in our application was to cast to a python `int` before indexing.

EDIT: Also note that numpy indexing returns the single value as was the case before this commit.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #967 by adding a check for scalar numpy types.

TODO:
* [X] Add unit tests and/or doctests in docstrings
* [X] Add docstrings and API docs for any new/modified user-facing classes and functions
* [X] New/modified features documented in docs/tutorial.rst
* [X] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
(Thanks, @benjeffery. Triggered the tests)

**Comment by benjeffery** [comment]
Sorry I missed the linting in the dev guide. I can recommend https://pre-commit.com/ for these type of checks, we use it heavily over at tskit: https://github.com/tskit-dev/tskit/blob/main/.pre-commit-config.yaml

**Comment by joshmoore** [comment]
@benjeffery : in general, big :+1: for pre-commit from my side (and maybe a :-1: for using the GH editor 🙂 )

**Comment by joshmoore** [comment]
Proposing to get this out ASAP as 2.11.1

**Pull request merged**
