### PR TITLE
Restore Flake8 configuration

### PR DESCRIPTION
**Pull request by jakirkham**
This was accidentally dropped when removing `tox` ( https://github.com/zarr-developers/zarr-python/pull/1219 ). Here we add a `.flake8` configuration file with those options. Note it is not currently possible to use `pyproject.toml` for Flake8 ( https://github.com/PyCQA/flake8/issues/234 ).

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
@Saransh-cpp, could you please review? 🙂

**Comment by joshmoore** [comment]
Humorous (?) sidenote: https://pypi.org/project/Flake8-pyproject/

**Comment by jakirkham** [comment]
Yeah saw that. For now think it is ok to keep this in a separate config file.

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @jakirkham!

`flake8`'s config is currently stored in `pre-commit-config.yaml`, and the contributing docs don't instruct developers to use `flake8` outside of `pre-commit`. There shouldn't be any issues with having it in 2 places though (similar to the codespell configuration)! 🚀

**Comment by jakirkham** [comment]
Ah ok. Thanks Saransh! 🙏

Will `flake8` read the config from `pre-commit-config.yaml`? Or if not, is there a way for us to point pre-commit at `.flake8`?

**Comment by Saransh-cpp** [comment]
> Will flake8 read the config from pre-commit-config.yaml? Or if not, is there a way for us to point pre-commit at .flake8?

Unfortunately, no and no 🥲

`pre-commit.ci` also has some problems with reading configurations from files other than `pre-commit-config.yaml`. I guess having this at two places is the only viable option right now.

**Comment by joshmoore** [comment]
Maybe let's minimally document those lines that require synchronization (and we'll keep looking for unified solutions moving forward)?

**Comment by jakirkham** [comment]
Gotcha thanks for looking into this Saransh! :pray:

Yeah would suggest raising [a new community issue]( https://github.com/zarr-developers/community/issues/new ) about using `pre-commit`. Maybe others have thoughts on this too 🙂

Let's go ahead and merge this change for `flake8` so we have it.

**Pull request merged**
