### PR TITLE
2.9.0 release notes

### PR DESCRIPTION
**Pull request by joshmoore**
With #773 now merged (:tada:), I'd like to get this out (today? Even thought it's a Friday?!) but it's a fairly big one. Any thoughts? Would anyone want an RC to test with?

### CODE REVIEW

**Comment by bnavigator** [comment]
Hi, I just tested to build your 2_9_0 branch for a package for openSUSE Tumbleweed (which has fsspec 2021.7.0) and I still get

```
[   89s] FAILED zarr/tests/test_core.py::TestArrayWithFSStoreNested::test_array_2d - A...
[   89s] FAILED zarr/tests/test_core.py::TestArrayWithFSStoreNestedPartialRead::test_array_2d
[   89s] FAILED zarr/tests/test_storage.py::TestFSStore::test_create - AttributeError:...
```

(#786, #802)

With #802 applied, the test_array tests pass, only test_create still fails.

Could you try to include #802 into the release and fix the last one (here or in fsspec) please?

**Comment by bnavigator** [comment]
I just found out, that https://github.com/intake/filesystem_spec/pull/710 should fix the test_create failure.

**Comment by joshmoore** [comment]
Hey @bnavigator. Thanks for giving this a try!

> I just found out, that [intake/filesystem_spec#710](https://github.com/intake/filesystem_spec/pull/710) should fix the test_create failure.

Agreed. Just waiting on the next release.

> Could you try to include #802 into the release and fix the last one (here or in fsspec) please?

Do you agree #802 is only needed if one bumps fsspec to 2021.7.0? So, if fsspec is pinned to 2021.6 or earlier (or one installs from the mainline) that 2.9.0 currently works?

**Comment by bnavigator** [comment]
> Do you agree #802 is only needed if one bumps fsspec to 2021.7.0? So, if fsspec is pinned to 2021.6 or earlier (or one installs from the mainline) that 2.9.0 currently works?

Yes, but pinning to an earlier version is not an option for openSUSE Tumblewee. Other packages already triggered the update of fsspec to 2021.7 causing the python-zarr to fail. If you are not going to merge #802 into 2.9.0, I will have to apply the patch to our package manually.

**Comment by joshmoore** [comment]
Agreed. Let's not include #802 just yet. I imagine an fsspec release will be along soon.

Merging and moving forward with the release.

**Comment by bnavigator** [comment]
For the record: `test_core::*::test_array_2d` still fail on 2.9.0 with fsspec-2021.7 and https://github.com/intake/filesystem_spec/pull/710 applied to it. You still need #802 with a new fsspec release.

**Pull request merged**
