### PR TITLE
Raise informative error when chunk size 0 

### LINKED ISSUE #303: Empty array & chunk definition
```
import zarr

store = zarr.DirectoryStore('data')
r = zarr.open_group(store=store)

z1 = r.full('V1', None,
            shape=(0,),
            chunks=None,
            dtype='i4',
            compressor=None)

print(z1[:])

z2 = r.full('V2', None,
            shape=(1,),
            chunks=(None,),
            dtype='i4',
            compressor=None)

print(z2[:])

z3 = r.full('V3', None,
            shape=(0,),
            chunks=(None,),
            dtype='i4',
            compressor=None)

print(z3[:])
```

#### Problem description

An exception is raised when array has a length of 0 & chunk is specified using ` (None,)` .
Result of above code:
```

[]
[897988541]
Traceback (most recent call last):
  File "/home/tom/PycharmProjects/starling-hcs/forest-penrose-zcube/examples/example_raster.py", line 31, in <module>
    print(z3[:])
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 559, in __getitem__
    return self.get_basic_selection(selection, fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 685, in get_basic_selection
    fields=fields)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/core.py", line 725, in _get_basic_selection_nd
    indexer = BasicIndexer(selection, self)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 279, in __init__
    dim_indexer = SliceDimIndexer(dim_sel, dim_len, dim_chunk_len)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 113, in __init__
    self.nchunks = ceildiv(self.dim_len, self.dim_chunk_len)
  File "/home/tom/anaconda3/lib/python3.6/site-packages/zarr/indexing.py", line 97, in ceildiv
    return int(np.ceil(a / b))
ZeroDivisionError: division by zero
```

#### Version and installation information

python 3.6
zarr 2.2.0
numcodecs 0.5.5
Ubuntu

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR checks if any dimension has a chunk size of 0 during the chunk normalization process and raises an informative error accordingly. Closes #303.

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [x] Docs build locally (e.g., run ``tox -e docs``)
* [x] AppVeyor and Travis CI passes
* [x] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Gentle ping @alimanfoo @jakirkham whenever you get a moment post-CZI application madness ; )

**Comment by alimanfoo** [comment]
Thanks @jrbourbeau, I'll take a look first thing next week :-)

**Comment by jakirkham** [comment]
What if we have an array with shape `(4, 0)`? Should we allow a size `0` chunk in this case?

**Comment by jrbourbeau** [comment]
That's a good questions. I'm not sure whether or not it makes sense for `zarr` to support these cases. 

One option would be to update this PR to raise a `NotImplementedError` with `"..is not currently supported"` instead of `"..is not supported"` and have a discussion in another issue re: allowing size `0` chunks

**Comment by joshmoore** [comment]
Things are green again here. FWIW I'm also missing the need to support 0-dimensions, but I assume it helps with numpy compatibility. https://github.com/zarr-developers/zarr-python/commit/445893ce53bcd519360686d5bf7f186518b14391 might be an option to deal with @jakirkham's comment.

**Comment by jakirkham** [comment]
Added a small test to ensure empty arrays can be created without issues.

**Comment by jhamman** [comment]
This has unfortunately gone stale. Seems like it was very close. Will it be revived or should we close this?

cc @jrbourbeau and @jakirkham

**Comment by jhamman** [comment]
Closing this out as stale. We'll keep the feature request open.

**Pull request closed without merging**
