### PR TITLE
Msgpack docs

### LINKED ISSUE #1187: Pytest Error when running TestSuite due to MsgPack
I think the instruction to install msgpack should be included in the installation docs when trying to install zarr from source code for development purpose.

### PR DESCRIPTION
**Pull request by GbotemiB**
Fixes #1187

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks for the PR, @GbotemiB. But if this only appears when running the tests, then I think would be more appropriate to add document around using `requirements_dev_minimal.txt` (and possibly `windows_conda_dev.txt` when using conda)

**Comment by joshmoore** [comment]
_Another_ option (that others may want to comment on) would be to make the msgpack tests optional.

**Comment by GbotemiB** [comment]
HI @joshmoore, What i did instead is to add the msgpack dependency to setup.py since we the issue is encountered when running setup.py

**Comment by jakirkham** [comment]
Maybe we should just make this a hard requirement in Numcodecs? Currently it is just a soft requirement there

**Comment by GbotemiB** [comment]
Hi @jakirkham, can you brief me on how to make it a hard requirement in Numcodecs?

**Comment by jakirkham** [comment]
We would move [the `extras_require`]( https://github.com/zarr-developers/numcodecs/blob/a3e05fd36f2cd7a2c903c4d5d9f787961a7a5905/setup.py#L345 ) into [`install_requires`]( https://github.com/zarr-developers/numcodecs/blob/a3e05fd36f2cd7a2c903c4d5d9f787961a7a5905/setup.py#L339 ). We may also need to add it to some requirements files (like [the RTFD requirements]( https://github.com/zarr-developers/numcodecs/blob/c78ff5360ac2db7876ac869990afe4c398a757f0/requirements_rtfd.txt )).

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks @GbotemiB! 🙏

**Pull request merged**
