### PR TITLE
try to install azurite on github action

### PR DESCRIPTION
**Pull request by Carreau**
Again to get back to our 100% coverage.

### CODE REVIEW

**Comment by jhamman** [comment]
@Carreau - per your request, here's a smallish-public Zarr store on Azure: 

```python
store = zarr.storage.ABSStore('carbonplan', prefix='carbonplan-share/zarr-demo', account_name='carbonplan')
zarr.open_consolidated(store)
```

Unfortunately, as I've just learned while preparing this snippet for you, you also need to provide the `account_key` kwarg in Zarr's interface. So I'm not sure how useful this will be for you. FWIW, adlfs doesn't require the `account_key` for public containers.

**Comment by Carreau** [comment]
Thanks super useful, it seem that querying `''` on this instance works, but not on azurite. 
So likely an azurite problem, I'll try to get an older impl of the package.

**Comment by jhamman** [comment]
I wonder if #620 would fix the problem you are seeing with the empty string query.

**Comment by Carreau** [comment]
> I wonder if #620 would fix the problem you are seeing with the empty string query.

Possibly. I can have a look once we are back on track with testing.

**Comment by Carreau** [comment]
This increases coverage; and I've open 681 to track reverting the xfail commits.

**Pull request merged**
