### PR TITLE
Fix N5Store.__contains__

### PR DESCRIPTION
**Pull request by gsakkis**
Fixes minor bug in `N5Store`

### CODE REVIEW

**Comment by alimanfoo** [comment]
Looks good to me but would be good if @funkey or @axtimwalde could confirm.

**Comment by united-against-covid** [comment]
Looks good, thanks for catching this!

**Comment by funkey** [comment]
Looks good, thanks for catching this!

**Comment by alimanfoo** [comment]
Thanks @gsakkis.

**Comment by jakirkham** [comment]
Thanks! 😄

**Pull request merged**
