### PR TITLE
Update CoC to the latest version

### PR DESCRIPTION
**Pull request by MSanKeys963**
Hi everyone! 👋🏻 

~~This PR updates the CoC to the same version as in [here](https://github.com/zarr-developers/.github/blob/main/CODE_OF_CONDUCT.md).~~

As discussed in https://github.com/zarr-developers/zarr-python/pull/1572#issuecomment-1830273746, I've removed the `CODE_OF_CONDUCT.md` from the Zarr-Python repository.

Please see https://github.com/zarr-developers/.github/pull/2 for more details. Thanks!

TODO:
* [ ] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by jhamman** [comment]
Q: do we need to duplicate this document in the Zarr-Python repo? Won't the parent organizations CoC apply here?

**Comment by MSanKeys963** [comment]
> Q: do we need to duplicate this document in the Zarr-Python repo? Wont the parent organizations CoC apply here?

Good point, @jhamman. I don't mind using the organisation-wide CoC for Zarr-Python and other repositories.
It's just that I happened to see the COC document in here and thought of syncing it.

**Comment by joshmoore** [comment]
* :+1: for pointing to the existing.
* Just noticed https://github.com/zarr-developers/numcodecs/blob/main/CODE_OF_CONDUCT.md could use updating, too. :wink:

**Comment by MSanKeys963** [comment]
Thanks, @joshmoore.

> Just noticed https://github.com/zarr-developers/numcodecs/blob/main/CODE_OF_CONDUCT.md could use updating, too. 😉

I've already added https://github.com/zarr-developers/numcodecs/pull/488 for this. ^

**Comment by joshmoore** [comment]
But wasn't @jhamman's point that these files might not need to be duplicated across multiple repos?

**Comment by MSanKeys963** [comment]
Yes. I think we need to make a decision for this.

If we're going to use the organisation-wide CoC, I'll update the PR and remove the CoC from the Zarr-Python repo.

**Comment by jhamman** [comment]
We already have the org-wide CoC: https://github.com/zarr-developers/.github/blob/main/CODE_OF_CONDUCT.md

So full support on removing this doc here. GitHub will pick the org-wide CoC up in all repositories that don't have their own.

**Comment by MSanKeys963** [comment]
Thanks, @jhamman.

Updated this and https://github.com/zarr-developers/numcodecs/pull/488.

**Review by jhamman — APPROVED** [review]

**Comment by joshmoore** [comment]
Thanks, guys.

**Pull request merged**
