### PR TITLE
Activate Python 3.9

### LINKED ISSUE #629: Test on Python 3.9
Python 3.9 has been released, it is now time to start enabling it in CI once available.

### PR DESCRIPTION
**Pull request by joshmoore**
In an attempt to track down https://github.com/zarr-developers/zarr-python/issues/858
Closes #629

TODO:
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Ok. Now down to just the codecov issue. The next clue in debugging is that:

```
        nbytes, self.cbytes, blocksize = cbuffer_sizes(header)
```
appears to now return matching values for `nbytes` and `blocksize` with the numcodecs update. That feels significant. Not sure if related to https://github.com/zarr-developers/numcodecs/pull/283

**Comment by andrewfulton9** [comment]
@joshmoore, sorry I missed my mention earlier. It looks like something in has changed to cause `nbytes` to always be the same as `blocksize`. It definitely could be [zarr-developers/numcodecs#283](https://github.com/zarr-developers/numcodecs/pull/283). I'll have to look closer to be sure though.

**Comment by jakirkham** [comment]
Oh interesting, meaning that Blosc may have changed something, which is affecting us here?

**Comment by andrewfulton9** [comment]
It looks like maybe Blosc has changed the default to just use 1 block if blocksize isn't defined so nbytes will equal blocksize by default, where previously it used to use some default (or tried to guess an optimum) blocksize. In `TestArrayWithFSStoreNested` I just used the [default block object](https://github.com/zarr-developers/zarr-python/blob/a92550b9ff9f4931353b4066486aaf9755895ce3/zarr/tests/test_core.py#L2711) so that is probably why nbytes always equals blocksize now. I can make a PR defining a blocksize there to see if that fixed it.

**Comment by jakirkham** [comment]
Think that would be helpful. We'd like to keep the partial read functionality in good working order 🙂

**Comment by joshmoore** [comment]
With #867 merged, this is now green. Merging (but #858/debian-failure) is still a mystery.

**Comment by jakirkham** [comment]
Thanks Josh! 😀

**Pull request merged**
