### PR TITLE
Support Python 3.8

### PR DESCRIPTION
**Pull request by jakirkham**
Begin testing and supporting Python 3.8.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] Docs build locally (e.g., run ``tox -e docs``)
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
CI fails because there are no `h5py` wheels on Python 3.8 yet.

**Comment by jrbourbeau** [comment]
Just pushed a commit to fix a release note merge conflict (hope that's okay). Now that there are `h5py` wheels for Python 3.8 (https://github.com/h5py/h5py/issues/1410), hopefully CI will be happy

**Comment by jakirkham** [comment]
Of course! Thanks for doing that James. 😄

Would you have a chance to review as well? Want to make sure we got all of these 🙂

**Comment by jrbourbeau** [comment]
Yeah, for sure! I'll make time to look at this tomorrow

**Comment by jakirkham** [comment]
Thanks @jrbourbeau! 😀

**Pull request merged**
