### PR TITLE
Un-pin numpy

### PR DESCRIPTION
**Pull request by dstansby**
I pinned numpy in a previous PR because it was breaking tests 😭 . This un-pins it to see what's going wrong, and then hopefully fix it.

### CODE REVIEW

**Comment by d-v-b** [comment]
numpy 2.2 changes the string repr for arrays (shape info is now displayed), maybe that's the culprit?

**Comment by dstansby** [comment]
From memory that's exactly it

**Comment by dcherian** [comment]
If you have the env, then running [`pytest-accept`](https://github.com/max-sixty/pytest-accept) should quickly fix it

**Comment by dstansby** [comment]
Ah amazing, thanks for sharing! https://github.com/scientific-python/pytest-doctestplus does a similar thing, but I'll checkout pytest-accept too

**Review by dcherian — APPROVED** [review]

**Pull request merged**
