### PR TITLE
More extensive orthogonal indexing in get/setitem

### PR DESCRIPTION
**Pull request by AndreasAlbertQC**
Addresses #1029 

Added getitem/setitem pass-through to orthogonal indexing for the following cases:
* index is iterable of integers
* index is iterable of length ndim, with each element being a slice, integer, or list. Maximum one list.

TODO:
* [X] Add unit tests ~and/or doctests in docstrings~
* ~~Add docstrings and API docs for any new/modified user-facing classes and functions~~
* [X] New/modified features documented in docs/tutorial.rst
* [X] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203882141347615

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @jni (in case this is of interest 🙂)

**Comment by joshmoore** [comment]
Agreed, I think @jni will be happy to see someone taking up the mantle!

**Comment by AndreasAlbertQC** [comment]
Thanks @jakirkham , @joshmoore. Please let me know if anything else is needed from my side. I figure I will resolve the conflicts after code review, so I can do it in one go rather than piecemeal.

**Review by jni — APPROVED** [review]
Brilliant stuff @AndreasAlbertQC! I have to admit I don't know the numpy rules in enough detail to properly grok all the case 2 conditions, but the tests test all of the questions I might have thoroughly so I'm happy with this. Major usability win. 😊

**Comment by joshmoore** [comment]
Thanks, @jni! Fixed the releases.rst conflict.

**Comment by AndreasAlbertQC** [comment]
Thank you!

**Pull request merged**
