### PR TITLE
Added website link

### PR DESCRIPTION
**Pull request by steph237**
[Description of PR]

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Review by joshmoore — CHANGES_REQUESTED** [review]
Hi @steph237. Thanks for the PR! I think, however, that you've unintentionally added some files here. See the screenshot below. It looks like you were testing locally and created an `a.zarr` and a `b.zarr` dataset which were committed. If you can remove those, it will be much easier to review your change.

Screen Shot 2022-10-23 at 19 19 42

**Comment by steph237** [comment]
> Hi @steph237. Thanks for the PR! I think, however, that you've unintentionally added some files here. See the screenshot below. It looks like you were testing locally and created an `a.zarr` and a `b.zarr` dataset which were committed. If you can remove those, it will be much easier to review your change.
> 
> Screen Shot 2022-10-23 at 19 19 42

@joshmoore Thank you for the review, I have removed the files

**Review by joshmoore — CHANGES_REQUESTED** [review]
Hi @steph237. Thanks for removing the files. In some repositories, you might be asked to "undo" or "rollback" the changes. (Here it's ok since we "squash" all the changes before committing them)

Can you please restore the "contributing.rst" file and revert back the "basepython" change?

Thanks.

Screen Shot 2022-10-24 at 08 12 25

**Comment by joshmoore** [comment]
> @joshmoore can i close this PR and open another just with the files which I have changed and with all the feedback ?

Definitely. That would be fine. But since I'm here....


Closing in favor of #1216

**Pull request closed without merging**
