### PR TITLE
Add documentation for find/findall using visit

### LINKED ISSUE #188: Document find, findall methods using visit()
Maybe useful to have methods "find" and "findall" on Group class to search for members (descendants?) matching some name query.

----

2022 Update: See the examples below on how to implement the method using `visit()`. These should be included in the documentation.

### PR DESCRIPTION
**Pull request by caviere**
Resolves #188

### CODE REVIEW

**Comment by caviere** [comment]
In `docs/`, on running:
```
make clean
make html
```
I get the following error:
```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v5.3.0
making output directory... done
[autosummary] generating autosummary for: api.rst, api/attrs.rst, api/codecs.rst, api/convenience.rst, api/core.rst, api/creation.rst, api/hierarchy.rst, api/n5.rst, api/storage.rst, api/sync.rst, contributing.rst, index.rst, installation.rst, license.rst, release.rst, spec.rst, spec/v1.rst, spec/v2.rst, spec/v3.rst, tutorial.rst
loading intersphinx inventory from https://docs.python.org/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 20 source files that are out of date
updating environment: [new config] 20 added, 0 changed, 0 removed
reading sources... [100%] tutorial
/home/kinya/zarr-python/zarr/hierarchy.py:docstring of zarr.hierarchy.Group.visit:41: ERROR: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorial
generating indices... genindex py-modindex done
highlighting module code... [100%] zarr.sync
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
```

**Comment by joshmoore** [comment]
The build is happy again, @caviere, (:+1:) but it looks like the formatting of the tree is squished:

Screen Shot 2022-11-03 at 13 44 52

**Comment by caviere** [comment]
I forgot to check how the docs look on the browser. I have now fixed it after reading on how to add literal blocks for sphinx https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks

**Comment by joshmoore** [comment]
This is great, @caviere. Thanks for doing the research and getting it into the docs!

**Pull request merged**
