### PR TITLE
Move codespell options around

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Starting with codespell 2.2.2, options can be specified in `pyrpoject.toml` in addition to `setup.cfg`:
https://github.com/codespell-project/codespell#using-a-config-file

Specifying options in a config file instead of command line options in `.pre-commit-config.yaml` ensures codespell uses the same options when run as pre-commit hook or from the command line in the repository root directory.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Mmmh... It looks like pre-commit does not run `codespell` from within the root directory as expected. I don't know enough about `pre-commit` and it doesn't work on Ubuntu 22.04 any way. Giving up for now.

**Comment by jakirkham** [comment]
cc @Saransh-cpp (in case you have feedback here 🙂)

**Comment by jakirkham** [comment]
As PR ( https://github.com/zarr-developers/zarr-python/pull/1197 ) touched these files earlier, this may need an update

**Comment by Saransh-cpp** [comment]
Maybe we can add the configuration in both of the files?

**Comment by DimitriPapadopoulos** [comment]
I am now able to run pre-commit on Ubuntu 22.04, but not sure how to check it works as the test is skipped:
```
$ pre-commit run codespell 
codespell............................................(no files to check)Skipped
$ 
```
I will probably have to introduce typos - temporarily.

**Comment by joshmoore** [comment]
> The problem with pre-commit is that it checks only the current commit...

@DimitriPapadopoulos, `pre-commit run -a` will explicitly run on all files.

**Comment by DimitriPapadopoulos** [comment]
Now I get this mysterious error:
```
$ pre-commit run -a
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
Check the log at /home/user/.cache/pre-commit/pre-commit.log
$ 
```
I cannot understand the error message
```
$ ls -l /home/user/.cache/pre-commit/pre-commit.log
-rw-rw-r-- 1 user user 1514 oct.   23 21:57 /home/user/.cache/pre-commit/pre-commit.log
$ 
```

**Comment by joshmoore** [comment]
Anything thoughts on these, @DimitriPapadopoulos?

```
notebooks/genotype_benchmark_compressors.ipynb:304: nD ==> and, 2nd
```
and
```
pyproject.toml:97: ihs ==> his
```

**Comment by DimitriPapadopoulos** [comment]
Not sure what you mean. Both `ihs` and `nD` are supposed to be skipped:
https://github.com/zarr-developers/zarr-python/blob/385b5d3635618e086eb4752f81c652379751a5ad/.pre-commit-config.yaml#L21

**Comment by joshmoore** [comment]
Sorry this are the current errors.

**Comment by DimitriPapadopoulos** [comment]
Do you mean in this specific branch [codespell](https://github.com/DimitriPapadopoulos/zarr-python/tree/codespell)? Yes, it is still a Draft. I cannot get the CI pre-commit run to use the repository root directory as the current directory and take into account `pyproject.toml`.

It souldn't be an issue on other branches though.

Besides, I am unable to run `pre-commit` locally, because Ubuntu lacks a `python` command by default, it only has `python3`:
```
$ pre-commit run -a
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:types-redis,types-setuptools.
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Executable `python` not found
stderr: (none)
Check the log at /home/user/.cache/pre-commit/pre-commit.log
$ 
```

**Comment by DimitriPapadopoulos** [comment]
I can run `pre-commit` using the workaround documented in [pre-commit giving error with mirrors-mypy, how do I fix it?](https://stackoverflow.com/questions/71291254/pre-commit-giving-error-with-mirrors-mypy-how-do-i-fix-it#73698579):
```
$ export SETUPTOOLS_USE_DISTUTILS=stdlib
$ 
$ pre-commit run -a
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/codespell-project/codespell.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
...
```

**Comment by joshmoore** [comment]
> Yes, it is still a Draft

Gotcha. Sorry for the noise. Was just into release mode on Monday :)

**Comment by DimitriPapadopoulos** [comment]
It appears to be working locally for me.

Both plain codespell and codespell run from pre-commit are now able to read settings from pyproject.toml. I guess the version of codespell in pre-commit has been updated ≥ 2.2.2.

**Review by jhamman — APPROVED** [review]

**Pull request merged**
