### PR TITLE
2.12.0 changelog

### PR DESCRIPTION
**Pull request by joshmoore**
Note on pre-releases:

An odd bug (or user error?!) with readthedocs leads to all pre-release anchors in the changelog to be reduced to just the final component (e.g. "a2"). Rather than struggle with this, this proposes to use the official anchor for the upcoming release, but to clearly mark it as a pre-release.

### CODE REVIEW

**Comment by joshmoore** [comment]
An additional question that goes along with this PR is whether we are ready to change the default branch from `2_11` back to main. Considering the fact that v3 is now solidly hidden, I would say quite likely.

**Review by MSanKeys963 — APPROVED** [review]

**Comment by MSanKeys963** [comment]
Looks good to me for now. I will be updating the links on the blog post [here](https://zarr.dev/blog/pre-release-2-12/) after this is merged.

**Comment by joshmoore** [comment]
Considering https://github.com/zarr-developers/zarr-python/pull/988#issuecomment-1164087963, I'm going to drop the "pre-release" parts of this PR and prepare 2.12.0.

**Comment by joshmoore** [comment]
Moving forward with 2.12.0 based on https://github.com/zarr-developers/zarr-python/pull/988#issuecomment-1164094946

**Pull request merged**
