### PR TITLE
Fix doc build warnings

### PR DESCRIPTION
**Pull request by dstansby**
Also fixes a `mypy` error, not sure why it's showing up here..

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks David! 🙏

Really appreciate the quick fix 😄

**Comment by dstansby** [comment]
Bah, it's still failing 😦

**Comment by jakirkham** [comment]
Hmm...only see a warning

```
WARNING: unknown mimetype for _static/donotdelete, ignoring
```

Is it converting the warnings to errors on branch builds?

**Comment by jakirkham** [comment]
The aforementioned warning is fixed with PR: https://github.com/zarr-developers/zarr-python/pull/1987

Appears with that change the builds now pass

**Pull request merged**
