### PR TITLE
WIP: Use NumPy's `fromfile` and `tofile`

### PR DESCRIPTION
**Pull request by jakirkham**
For reading and writing data on disk, start using NumPy's `fromfile` and `tofile`.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] Docs build locally (e.g., run ``tox -e docs``)
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi John, out of curiosity, what's the benefit here of using NumPy versus
plain open()?

**Comment by jakirkham** [comment]
This probably doesn't merit review ATM. It's part of some exploratory work I'm doing.

**Comment by alimanfoo** [comment]
Cool, no problem.

**Comment by jakirkham** [comment]
I think PR ( https://github.com/zarr-developers/zarr-python/pull/503 ) gets at the actual need a bit cleaner. So will close this out. Thanks for humoring me 🙂

**Pull request closed without merging**
