### PR TITLE
adding GitHub Action for Creating a Release on Tag push

### PR DESCRIPTION
**Pull request by julianavmgiusti**
[Description of PR]

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

Fixes https://github.com/zarr-developers/zarr-python/issues/1118

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @joshmoore

**Comment by joshmoore** [comment]
Thanks @julianavmgiusti! I'm not at my laptop for a day or two but my first questions would be: can this create a link to the release notes as the others do? and if someone creates a tag & release on the webpage will _another_ get created?

**Comment by joshmoore** [comment]
@julianavmgiusti: have you tested this out on your own repository?

**Comment by jhamman** [comment]
This has unfortunately gone stale. Will it be revived or should we close this?

**Comment by jhamman** [comment]
Closing this out as stale. We'll keep the original feature request open.

**Pull request closed without merging**
