### PR TITLE
Move V3 development to main

### PR DESCRIPTION
**Pull request by jhamman**
This PR moves the current `v3` branch to `main`. Following this merge, the following actions should be taken:

1. reset the default branch in this repo to `main`
2. remove the `v3` branch (this is an important signal to downstream testers that are currently using `@v3`
3. update our github actions to trigger off `main` instead of `v3`
4. update the target branch for PRs pointing at the `support/2.x` branch

closes https://github.com/zarr-developers/zarr-python/issues/2308

@zarr-developers/python-core-devs -- looking for two 👍 here.

### CODE REVIEW

**Review by d-v-b — APPROVED** [review]
image

🚀

**Comment by dstansby** [comment]
I'd like to advocate for branch named `v2` instead of `support/2.x` - `v2` is shorter to type, and mirrors the `v3` branch we've had going on for a while.

**Comment by jhamman** [comment]
@dstansby - the name of the support branch is somewhat independent of this PR but the reason I like having the `support` name in there is that it clearly defines the purpose of the branch -- supporting v2.

**Comment by dstansby** [comment]
I don't think it's orthogonal, because this PR proposes to switch `main` from a development branch for v2 to v3, and I think we should have consensus on the details of what is happening to v2 development (including branch name) before this gets merged. So please can we hold off this until https://github.com/zarr-developers/zarr-python/issues/2345 is resolved?

**Pull request merged**
