### PR TITLE
create hatch test env

### LINKED ISSUE #1648: [v3] Test environments and CI
We just merged #1592 which should make managing our various test environments much easier going forward. This ticket lays out a number of small tasks that can be taken to modernize our test environments and GitHub Actions Workflows. I'm sure I'm missing a few things here so feel free to comment / suggest alternatives.

### Hatch related improvements

- [x] Define dev environments in pyproject.toml using [Hatch environments](https://hatch.pypa.io/1.9/environment/)
  - Move `requirements_dev_*.txt` defining separate environments for "minimal", "dev". These should include parameterizations over python versions (3.10 and 3.11). 
  - Use these environments in our GitHub actions
- [x] Split out "minimal" environment into two separate environments
  - Minimum supported versions of all dependencies (see #1616)
  - Minimal dependencies (latest versions)
- [x] Create "docs" environment so developers can simply run: `hatch run docs:serve` 

### GitHub Actions related improvements

- [x] Explore removing the need to install a conda environment, instead relying on pure hatch environments
- [ ] Explore combining the "windows", "minimal", and "python-package" workflows into a single workflow
- [x] Run Mypy checks in each matrix run in addition to our pre-commit script

### PR DESCRIPTION
**Pull request by rabernat**
Closes #1648

### CODE REVIEW

**Comment by d-v-b** [comment]
anything I should wait on before merging?

**Comment by rabernat** [comment]
Lots! I am not done here. I thought this was a draft.

I'd like to get to a working GH action using the hatch test env.

**Comment by jhamman** [comment]
This did not run the test -- why is that?

**Comment by rabernat** [comment]
Because tests only run on main. We will need to completely redo the test environment using hatch. I intend to have an MPV version of that in a new workflow file as part of this PR.

**Review by d-v-b — APPROVED** [review]
looks great! in future PRs we can lean more into the configuration, but I love what we have already

**Pull request merged**
