### PR TITLE
Pre-commit configuration

### PR DESCRIPTION
**Pull request by Alt-Shivam**
[Description of PR]
Flake8 is already added.
and the following will be added soon.

With few changes
https://github.com/pre-commit/mirrors-mypy
https://github.com/adrienverge/yamllint.git
https://github.com/asottile/pyupgrade
With moderate changes
https://github.com/pre-commit/pre-commit-hooks
https://github.com/asottile/seed-isort-config
https://github.com/PyCQA/isort
With lots of changes
https://github.com/psf/black

### CODE REVIEW

**Comment by joshmoore** [comment]
Hi @Alt-Shivam. Thanks for starting this. Can you also add a .github/workflows change that executes the pre-commit so that we know it's working?

**Comment by Alt-Shivam** [comment]
Added. @joshmoore 
Please have a look.

**Review by joshmoore — APPROVED** [review]
Thanks, @Alt-Shivam! I'll not that we probably want to move to https://github.com/marketplace/pre-commit-ci rather than have our workflow, but for the moment, while we're investigating, :+1: for having this in place.

**Comment by Alt-Shivam** [comment]
Cheers @joshmoore 
Looking forward to adding more Pre-commit hooks in the future.

**Pull request merged**
