### PR TITLE
Fix Sqlite Store Wrong Modification

### PR DESCRIPTION
**Pull request by potter420**
Reference to issue #439

A quick fix to issue #439 

TODO:
* [x] Add unit tests and/or doctests in docstrings
* NA Add docstrings and API docs for any new/modified user-facing classes and functions
* NA New/modified features documented in docs/tutorial.rst
* NA Changes documented in docs/release.rst
* NA Docs build locally (e.g., run ``tox -e docs``)
* [x] AppVeyor and Travis CI passes
* [x] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for working on this fix @potter420. Could you please add tests for these changes?

**Comment by potter420** [comment]
@jakirkham  All done sir. Sorry for the delay. It is my first ever time committing anything on GitHub.

**Comment by jakirkham** [comment]
No need to apologize. Thanks for moving this forward. Will take a closer look and share any feedback. 🙂

**Comment by jakirkham** [comment]
Sorry for the delay. Thanks for the PR @potter420! 😄

**Pull request merged**
