### PR TITLE
Added Yaml Check in Pre-commit

### PR DESCRIPTION
**Pull request by Alt-Shivam**
Yaml check for pre-commit.
Related to #1015 and #1012

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @Alt-Shivam.

```
Check Yaml...............................................................Passed
```

Based on your previous comment, isn't it a bit surprising that there are no errors?

**Comment by Alt-Shivam** [comment]
Yes, @joshmoore Basically I used a different YAML checker in this case.
and this is slightly less strict and only checks the validity.

but in the previous case, the YAML linter is kind of strict one which checks line lengths, brackets, extra spaces and extra symbols in YAML

**Comment by Alt-Shivam** [comment]
I have done some tests with this one.
image

**Comment by Alt-Shivam** [comment]
I don't want to make lots of changes in the codebase, so I chose this one.
but If you like the strict one, Then I can also accommodate that one :)

**Comment by joshmoore** [comment]
Ah, fair enough. Let's keep https://github.com/adrienverge/yamllint.git on the long-term list, but :+1: for starting with the easier introductions.

**Pull request merged**
