### PR TITLE
Add key normalization to DirectoryStore and subclass stores

### LINKED ISSUE #319: Case insensitivity and DirectoryStore
The matching of keys in a DirectoryStore will depend on the underlying file system. If a DirectoryStore is running on a case-sensitive file system, as is usually default on most linux systems, then keys like 'foo' and 'FOO' will appear as distinct. However, if on a case-insensitive file system, as is usually default on mac and windows, then keys like 'foo' and 'FOO' will be considered as identical. I.e., if a key ``'foo'`` has been set, then ``'FOO' in store`` will return ``True``.

This is not a bug but a potential gotcha, as behaviour of code may vary between operating systems if multiple keys that are case insensitive equal are present in the data, and users are expecting case-sensitive behaviour. E.g., https://github.com/cggh/scikit-allel/issues/215 and https://github.com/ornl-oxford/genomics-benchmarks/issues/34.

At least this is something that needs to be documented. Not sure what more could be done.

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds an option to the `DirectoryStore` constructor, as well as to stores which inherit from `DirectoryStore` (i.e. `NestedDirectoryStore`, `TempStore`, and `N5Store`), to normalize store keys to all be treated as lower case. This can be useful to avoid potential discrepancies between case-senstive and case-insensitive file system.

Closes #319.

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [x] Docs build locally (e.g., run ``tox -e docs``)
* [x] AppVeyor and Travis CI passes
* [x] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Gentle ping @jakirkham @alimanfoo if you get a moment to give this a quick review. If we're okay with the name `normalize_keys` for this keyword argument, then I think this should be good to go.

**Comment by jakirkham** [comment]
Thanks working on this James! 😄

**Comment by jakirkham** [comment]
Sorry there was a bit of churn in the changelog. Could you please fix the conflict here?

**Comment by jrbourbeau** [comment]
Yeah, not a problem! Just resolved the conflicting file

**Comment by jrbourbeau** [comment]
Just wanted to give a ping that this PR should be good to merge

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
