### PR TITLE
Circumvent Codecov's legitimate complaint without resorting to pragma

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
Codecov recognises that we aren't testing with `fsspec`.  Perhaps it is less picky if we use `pytest.param` to parametrise the tests.

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] New/modified features documented in docs/tutorial.rst
* [x] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
As promised in https://github.com/zarr-developers/zarr-python/pull/821#issuecomment-904725427, this is now ready for review.

Apologies that my silly typo incurred an extra round of CI checks, redundantly chewing through more electrons than was necessary.

**Comment by joshmoore** [comment]
> redundantly chewing through more electrons than was necessary.

Heh. We need a CO2 counter per PR (and/or [`[skip ci]`](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/))

**Review by joshmoore — APPROVED** [review]
Thanks for the increase in sanity!

**Comment by jakirkham** [comment]
Ah good catch. Thanks for adding this Ben! 😄

**Pull request merged**
