### PR TITLE
Moving tutorial.rst to tutorial.ipynb

### PR DESCRIPTION
**Pull request by sudoyolo**
Hi everyone! 
This is in reference to #514.
I added the Jupyter Notebook in the Docs directory. 
I have not yet integrated the notebook with the readdocs output, its a WIP. 

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by MSanKeys963** [comment]
Thanks for submitting the PR @sudoyolo. Might I suggest changing the title of the PR to something more informative like, 'Moving `tutorial.rst` to `tutorial.ipynb`.

**Comment by jakirkham** [comment]
Maybe we should look at using [sphinx-gallery]( https://sphinx-gallery.github.io/stable/index.html ) or something

**Comment by sudoyolo** [comment]
I have been working on this issue for sometime now when it struck me, would it be a good idea if we were to directly put a Binder/Colab link for tutorial.ipynb in the tutorial.rst file? Or are we trying to replace tutorial.rst with tutorial.ipynb entirely?

**Comment by GbotemiB** [comment]
Hi @joshmoore I am from Outreachy and I will like to work on integrating the notebook into readthedocs.

**Comment by joshmoore** [comment]
Glad to hear it, @GbotemiB. For learning more about jupyter book, you might take a look at the original blog post: https://blog.readthedocs.com/jupyter-book-read-the-docs/

**Comment by melissakirabo** [comment]
Hi @joshmoore, I am from Outreachy as well and I am interested on taking on the notebook integration into readthedocs.

**Comment by MSanKeys963** [comment]
> Hi @joshmoore, I am from Outreachy as well and I am interested on taking on the notebook integration into readthedocs.

Hi @melissakirabo. Welcome, and thanks for your interest in Zarr.
Please refer to the blog post here: https://zarr.dev/blog/outreachy-contributer-guide/

We'll be over at Gitter to answer your questions. :)

**Pull request closed without merging**
