### PR TITLE
DOC: Minor tweak to advanced indexing example in tutorial

### PR DESCRIPTION
**Pull request by rossbar**
I just wanted to make a very minor suggestion I had while reading through the tutorial (which is very nice, thank you for that!):

In the advanced indexing section, the array used in the 1D examples is `np.arange(10)`. This means that the indices and corresponding values are the same. There's nothing wrong with this of course, but I thought the example might be more immediately grokkable if a different example array were used where the values were different than the indices. I arbitrarily chose `np.arange(10) ** 2`, but any other choice would be equally valid. This is of course a very minor point and pretty subjective, so please feel free to ignore!

I also added two other minor commits that popped up while running through the contributor guide to make the PR:
 - I noticed `virtualenv` was referenced, but the example uses the built-in `venv` module, so I removed it, and
 - Fixed a failing doctest due to a malformed comment.

Again - nothing major; please feel free to ignore/cherry-pick as you see fit!

### CODE REVIEW

**Comment by d-v-b** [comment]
Looks good to me! I'm going to merge in the next few days unless anyone else objects.

**Review by MSanKeys963 — APPROVED** [review]

**Comment by MSanKeys963** [comment]
Hi @rossbar. 👋🏻 
Good to see you here! 😄

Thanks for sending the PR. Everything looks good to me.
PS. If you have any additional suggestions, please let us know.

**Comment by joshmoore** [comment]
:+1: from my side as well. Only question I have, @rossbar, is whether or not you'd like to add yourself to the [release notes](https://github.com/zarr-developers/zarr-python/blob/main/docs/release.rst). The more the merrier!

**Comment by MSanKeys963** [comment]
Added release notes for this in #1574.
Good to go with this.

**Pull request merged**
