### PR TITLE
Automatically generate API reference docs

### PR DESCRIPTION
**Pull request by dstansby**
This uses [sphinx-autoapi](https://sphinx-autoapi.readthedocs.io/en/latest/index.html) to automatically generate API reference for v3, replacing a lot of manually created .rst pages that were present for v2. Currently only for the `zarr` namespace, but can (and should) be expanded to sub-modules in a follow up PR.

See https://zarr--1918.org.readthedocs.build/en/1918/api/index.html for the current build of this PR; feedback welcome. There are definitely improvements to be made here, but I think worth getting this in as a first go at the API reference.

### CODE REVIEW

**Comment by d-v-b** [comment]
I didn't review this in detail but i like the effort, and auto docs >>> no docs IMO

**Review by d-v-b — APPROVED** [review]

**Comment by d-v-b** [comment]
thanks @dstansby !

**Comment by jakirkham** [comment]
Thanks all! 🙏

It looks like RTD is failing. Would someone here be able to take a look? 🙂

**Comment by d-v-b** [comment]
@jakirkham I'm not too familiar with RTD but I can try to sort things out. Can you elaborate on where the problem is evident? E.g., what should I be looking at?

**Comment by dstansby** [comment]
See the v3 builds at https://app.readthedocs.org/projects/zarr/builds/. https://github.com/zarr-developers/zarr-python/pull/1985 should be a fix.

**Comment by jakirkham** [comment]
Thank you both! 🙏

Yep David linked the right place to look. As RTD will just show the last successful build, looking at the doc pages themselves is unfortunately not as helpful. Maybe they could have a banner to note the doc builds or failing or something

Have gone ahead and merged David's fix. Let's see if that helps 🍀

**Comment by jakirkham** [comment]
Fixed with PRs:

* https://github.com/zarr-developers/zarr-python/pull/1985
* https://github.com/zarr-developers/zarr-python/pull/1987

Doc builds are now passing again! 🎉

**Pull request merged**
