### PR TITLE
Adapt storage tests for changes in fsspec (#1819) (#1679)

### PR DESCRIPTION
**Pull request by AdamWill**
This is adapted from the fixes that were rolled into https://github.com/zarr-developers/zarr-python/pull/1785 for the v3 branch.

TODO:
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

Deleted TODO items are not applicable as this changes no code, only tests.

### CODE REVIEW

**Comment by AdamWill** [comment]
On v3 the check in `test_hierarchy` was commented out entirely, but that seems excessive to me. The comment indicates the primary point of these checks is to make sure they run without causing an assertion, and we can still do that, and check that the result is one of the two we know are possible.

**Comment by dstansby** [comment]
Thanks for this! To get the tests passing, I think the version of fsspec in `requirements_dev_optional.txt` will need increasing to a version that's compatible with the new tests.

**Comment by AdamWill** [comment]
ugh, it's been a while, but I *think* the change is supposed to work with both old and new fsspec? I'll try and find a minute to remember it...

**Comment by jhamman** [comment]
I'm going to close this as stale. Folks should feel free to reopen if there is interest in continuing this work.

**Comment by AdamWill** [comment]
yeah, looking at it again, this is intended to work both ways.

**Comment by AdamWill** [comment]
eh, but looking at the test results, it didn't. not sure why not, i'd have to remember all this stuff again. sigh.

**Pull request closed without merging**
