### PR TITLE
Update: added date types supported on tutorial docs

### PR DESCRIPTION
**Pull request by oguejioforO**
[Addition of date types supported by zarr]

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @oguejioforO. The supported datatypes are certainly something that tutorial readers need to be made aware of but I'm a bit concerned that:

 1. placing it at the beginning may slow readers down (_Could it be more of a footnote?_)
 2. and it may need more explanation (_Is there a link we could send people to?_).

**Comment by oguejioforO** [comment]
@Joshmoore, Thanks for the review will add it as a footnote and further explain them, I have no link to where it has been explained.

**Comment by oguejioforO** [comment]
@joshmoore, I have made the changes.

**Comment by joshmoore** [comment]
Thanks, @oguejioforO. Could you add a title to separate this section from the "Blosc" section?

**Comment by oguejioforO** [comment]
Alright will do that.

**Comment by jhamman** [comment]
This has unfortunately gone stale. Will it be revived or should we close this.

**Pull request closed without merging**
