### PR TITLE
Managing Authors/Contributors with Rever

### PR DESCRIPTION
**Pull request by GbotemiB**
This PR contains setup with rever to manage authors and contributors.
@joshmoore and @MSanKeys963 

To use rever to manage contributors.
authors activity has been configured in rever.xsh to track contributors.

run `rever setup` in root directory. This will create a AUTHORS file containing the names of all contributors, `.mailmap` file that contains the name of contributors mapped to their mail and .authors.yml file containing metadata about authors contribution.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Review by Saransh-cpp — COMMENTED** [review]
Why not use the [all contributors bot](https://allcontributors.org)? Remember, contributions to a project are not always in the form of commits, and we should be acknowledging all types of contributions. Also, this adds additional files to the root Zarr repository which looks redundant at first glance.

**Comment by GbotemiB** [comment]
> Why not use the [all contributors bot](https://allcontributors.org)? Remember, contributions to a project are not always in the form of commits, and we should be acknowledging all types of contributions. Also, this adds additional files to the root Zarr repository which looks redundant at first glance.

Hi @Saransh-cpp, thanks for the tip. Actually the goal is to use rever to automate releases. While automating releases, it could handle contributors list too. I will check to see if it acknowledges all types of contributions. 

Regarding the files, we could reduce the number of files.

**Review by Saransh-cpp — COMMENTED** [review]
This was in my GitHub's "review request" PR list, cleaning that up today 🙂

I don't really think a review is required from me here, but please ping me again if it is!

**Comment by jhamman** [comment]
This has unfortunately gone stale. Will it be revived or should we close this?

**Comment by jhamman** [comment]
Closing this out as stale. Feel free to reopen if there is interest in picking this up.

**Pull request closed without merging**
