### PR TITLE
FSStore: key_separator fix

### PR DESCRIPTION
**Pull request by joshmoore**
key_separator: fix handling of meta keys

    This rebases and cleans a fix from Martin's original PR.
    Two new test methods fail without it and pass with since
    keys for meta-files like `.zarray` were being converted
    into `/zarray`.

 see: https://github.com/martindurant/zarr/pull/1/commits/5795bc7368eb0b86aaeb1956ffed514e672db96e

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Doesn't look like restarting picks up the new commits to master. Trying a manual merge of master.

**Comment by jakirkham** [comment]
> Doesn't look like restarting picks up the new commits to master. Trying a manual merge of master.

Yeah I've noticed that about GH Actions. We can fix this manually either by doing it ourselves or adding it to GH Actions. Here's the same idea, but with CircleCI ( https://github.com/scikit-learn/scikit-learn/pull/8211 )

**Comment by joshmoore** [comment]
Nice idea!

**Review by martindurant — APPROVED** [review]

**Comment by joshmoore** [comment]
Thanks, @martindurant.

**Pull request merged**
