### PR TITLE
Fixed ArrayV2Metadata parameter names

### PR DESCRIPTION
**Pull request by TomAugspurger**
For things like dataclasses.repalce to work, we need the parameter names to match the attribute names.

All the name change between what we have in memory and what the specs requires should happen during serialization / deserialization.

Closes https://github.com/zarr-developers/zarr-python/issues/2269

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by d-v-b** [comment]
Can you show the problem that this PR solves? From my POV it's a good thing that the metadata classes have the same structure as the underlying zarr metadata document(s).

**Comment by TomAugspurger** [comment]
https://github.com/zarr-developers/zarr-python/issues/2269 has the issue. Doing something like `a.attrs.put({"key": 0})` or anything that uses `dataclasses.replace` will fail with

```python
TypeError: ArrayV2Metadata.__init__() got an unexpected keyword argument 'chunk_grid'
```

> From my POV it's a good thing that the metadata classes have the same structure as the underlying zarr metadata document

Would that mean changing the dataclass fields on `ArrayV2Metadata` to `chunks` and `dtype`? I'm guessing we have it this way currently is to support writing code that's generic over `ArrayV2Metadata` and `ArrayMetadata`. IMO, that's more important than having the Python data model exactly match the on-disk representation, since the translation should be isolated to just `to_dict` and `from_dict`.

**Comment by d-v-b** [comment]
I think a design goal for `ArrayV2Metadata` and `ArrayV3Metadata` is that they should be as independent as possible from whatever array API we layer on top of them. This ensures that `zarr-python` can evolve that array API in just one place (the array classes), and also ensures that `zarr-python` is more useful to libraries that want to work with the Zarr data model, but don't want to use the `zarr-python` array runtime classes.  IMO both of these are weakened if our in-memory array abstraction leaks onto the metadata classes.

**Comment by TomAugspurger** [comment]
> I think a design goal for ArrayV2Metadata and ArrayV3Metadata is that they should be as independent as possible from whatever array API we layer on top of them

Mmm, I'm not sure where I stand on that :) I think I agree that it's nice to have something that directly models the stored representation of the data, or is at least trivially convertible to it (and I'd count renaming the key as trivial). But IMO the most important thing is the ability to write code that's generic over v2 and v3. I don't have a strong preference for whether that's achieved by having subtypes with mostly the same interface (ArrayV2Metadata and ArrayV3Metadata using the same field names) or some wrapper class.

I'll leave this on hold for now.

**Comment by TomAugspurger** [comment]
Converting this to draft while https://github.com/zarr-developers/zarr-python/pull/2301 is worked on. But we'll want to confirm that this original issue here is fixed.

**Comment by TomAugspurger** [comment]
This was superseded by #2301.

**Pull request closed without merging**
