### PR TITLE
Test on Python 3.9-dev, also remove sudo

### PR DESCRIPTION
**Pull request by Carreau**
3.9 have been release a few weeks ago, and sudo seem unnecessay.

### CODE REVIEW

**Comment by Carreau** [comment]
Seem to fail because of h5py.

**Comment by Carreau** [comment]
libh5py does not seem to work yet on 3.9

**Comment by jakirkham** [comment]
Would xfailing some tests on Python 3.9 help?

**Comment by Carreau** [comment]
> Would xfailing some tests on Python 3.9 help?

Yeah, likely or maker them skipif if we can't import h5py. Right now it's more a question on conditionally trying to install h5py as CI fails before starting the tests.

**Comment by jakirkham** [comment]
Guessing this will need an update to move to GH Actions

**Comment by joshmoore** [comment]
Yeah, actually, looking at it, I'm not sure it's worth keeping it around. Closing. If anything is salvageable, let's do that in a new PR.

**Pull request closed without merging**
