### PR TITLE
DOC: fix typo in code snippet

### PR DESCRIPTION
**Pull request by llllllllll**
Add missing closing parenthesis in code snippet.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] Docs build locally (e.g., run ``tox -e docs``)
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Nice catch! Thanks @llllllllll 😄

**Comment by llllllllll** [comment]
Thanks for merging!

**Comment by jakirkham** [comment]
Would be curious to hear how playing with Zarr has gone for you. 🙂

**Comment by llllllllll** [comment]
I would love to talk about how I plan on using zarr and how it is going. What would be the best way to do that?

**Comment by jakirkham** [comment]
We could setup a video chat. Would you have some time this week or next?

**Comment by llllllllll** [comment]
Yeah, can you email me at `joe@quantopian.com` to schedule something?

**Pull request merged**
