### PR TITLE
`open_array()`: adding the `meta_array` argument

### PR DESCRIPTION
**Pull request by madsbk**
Like the other creation functions, `open_array()` now takes the  `meta_array` argument.

TODO:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] Changes documented in docs/release.rst
* [x] GitHub Actions have all passed
* [x] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by quasiben** [comment]
@rabernat i think this is the last piece needed for xarray/GDS support

**Comment by quasiben** [comment]
Would it be possible to include this in the 2.15 Zarr release ?

**Comment by joshmoore** [comment]
Makes sense to me to have it with your other PR, @madsbk. (Sidenote: 2.15a1 just went out)

**Comment by madsbk** [comment]
> Makes sense to me to have it with your other PR, @madsbk. (Sidenote: 2.15a1 just went out)

Agree, it would be great to get this in `v2.15`!

**Comment by joshmoore** [comment]
@madsbk: quick higher-level question -- how many other locations do you think might need this?

**Comment by madsbk** [comment]
Anything that needs to be done here?

**Comment by joshmoore** [comment]
Hi @madsbk. Apologies. I took a look after your last push, but the Windows 3.11 build was failing and a re-run didn't fix it (and then I promptly got side-tracked).

I just re-ran and all is green. Let's get this in. I'll push out an immediate pre-release and then review the state of everything tomorrow. (Feedback on a full release of 2.15.0 welcome from any/all.)

Thanks for hanging in there!

**Comment by madsbk** [comment]
Awesome, thanks @joshmoore !

**Pull request merged**
