### PR TITLE
Update GitHub Actions

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Will have to address compatibility issues.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [X] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Something looks odd on Windows

```
creating zarr-0.1.dev1
```

**Comment by DimitriPapadopoulos** [comment]
Not sure where `creating zarr-0.1.dev1` comes from...

**Comment by DimitriPapadopoulos** [comment]
@Saransh-cpp I have squashed into a single commit including your fix.

**Comment by DimitriPapadopoulos** [comment]
And I have added automated future updates, see `.github/dependabot.yml`.

**Comment by DimitriPapadopoulos** [comment]
Why [Merge branch 'main' into actions](https://github.com/zarr-developers/zarr-python/pull/1134/commits/8767e65aebdfa41dae1ab078ae8e0b998ef09974)? This results in additional pipeline runs, and the same can be achieved with rebasing when merging.

**Comment by jakirkham** [comment]
Because GitHub was complaining the branch was out-of-date. So tried to help out here. Though feel free to rebase or do whatever is preferred

**Comment by DimitriPapadopoulos** [comment]
Thank you. A new code review is needed, if any of you has some time to spend on this issue.

**Comment by joshmoore** [comment]
Thanks as always, @DimitriPapadopoulos!

**Pull request merged**
