### PR TITLE
Use full config dict for default codecs

### PR DESCRIPTION
**Pull request by normanrz**
Builds upon #2463 

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by normanrz** [comment]
See https://github.com/zarr-developers/zarr-python/pull/2584/commits/5cb6dd8f62ad6ed5391a08535dc05ef9ac50bbad

**Review by d-v-b — APPROVED** [review]

**Comment by d-v-b** [comment]
this looks good @normanrz; we probably don't want to merge this as-is, would you recommend that I bring https://github.com/zarr-developers/zarr-python/commit/5cb6dd8f62ad6ed5391a08535dc05ef9ac50bbad in to #2463 ?

**Comment by jhamman** [comment]
I also agree that this looks good. Let's manually merge into @d-v-b's PR and do a final review there.

**Comment by normanrz** [comment]
Yes, please merge jnto your PR @d-v-b

**Comment by normanrz** [comment]
Merged into https://github.com/zarr-developers/zarr-python/pull/2463. Closing here.

**Pull request closed without merging**
