### PR TITLE
Turned on isolated_build in tox.ini file

### PR DESCRIPTION
**Pull request by DON-BRAN**
fixes: #1209

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @DON-BRAN. Any idea why the build in #1158 didn't detect this?

**Comment by Saransh-cpp** [comment]
Hmm, I think Zarr is not using `tox` in GitHub Action to run the tests or to build the package.

**Comment by DON-BRAN** [comment]
> Thanks, @DON-BRAN. Any idea why the build in #1158 didn't detect this?

Hello @joshmoore, I'm not sure of why the build at https://github.com/zarr-developers/zarr-python/pull/1158 didn't detect this behavior. I came across some resources

https://tox.wiki/en/latest/example/package.html
https://github.com/tox-dev/tox/issues/1523
https://github.com/pypa/pip/issues/8437

**Comment by joshmoore** [comment]
> Hmm, I think Zarr is not using `tox` in GitHub Action to run the tests or to build the package.

That would certainly do it, @Saransh-cpp. :smile: I've filed https://github.com/zarr-developers/zarr-python/issues/1211

**Comment by joshmoore** [comment]
Getting this merged since others (like @steph237) have needed to set this flag in their PRs.

**Pull request merged**
