### PR TITLE
black -> ruff format + cleanup

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Ruff can now format files. Ruff formatter is much faster than black.

Other changes are good practices recommended by scientific python.

TODO:
* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in docs/tutorial.rst
* [ ] Changes documented in docs/release.rst
* [ ] GitHub Actions have all passed
* [ ] Test coverage is 100% (Codecov passes)

### CODE REVIEW

**Review by d-v-b — APPROVED** [review]
Thanks! This looks good to me

**Comment by joshmoore** [comment]
I'm struggling to get the Windows 3.9 build to pass:

```
E   ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
```

There are similar issues like https://github.com/pyca/cryptography/issues/9444 and https://github.com/PyO3/pyo3/issues/3425

**Comment by jhamman** [comment]
@Saransh-cpp - could I convince you to reorient this PR to the v3 branch? I'm very much hoping that the release we are preparing now is the last in the 2.* series which makes this change likely to go out of date quickly.

**Comment by Saransh-cpp** [comment]
I think the workflow failures are unrelated to this PR?

**Comment by jhamman** [comment]
@Saransh-cpp - try pulling the v3 branch once more. We made a lot of progress on the v3 branch CI last week so things should be good to go.

**Comment by Saransh-cpp** [comment]
Thanks, @jhamman! Could you please let me know if the new errors in the CI are related to my PR?

**Comment by joshmoore** [comment]
> Could you please let me know if the new errors in the CI are related to my PR?

I think not.

```
self = <tests.test_core.TestArrayWithLMDBStoreNoBuffers object at 0x7f7d673616f0>

    def create_store(self):
>       pytest.importorskip("lmdb")
E       Skipped: could not import 'lmdb': No module named 'lmdb'

tests/test_core.py:2073: Skipped

During handling of the above exception, another exception occurred:

self = <tests.test_core.TestArrayWithLMDBStoreNoBuffers object at 0x7f7d673616f0>

    def test_object_codec_warnings(self):
>       with pytest.warns(UserWarning):
E       Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) were emitted.
E        Emitted warnings: [].
```

looks very much like a problem I've been trying to solve on the mainline:

https://github.com/zarr-developers/zarr-python/pull/1621/commits/37e6e1fb516707bf01c15fe3f3bc2f9062e4c061

**Comment by Saransh-cpp** [comment]
Thanks!

**Comment by jhamman** [comment]
@Saransh-cpp - this seemed really close. Can you resolve the conflicts and we can get it in.

**Comment by Saransh-cpp** [comment]
pre-commit.ci autofix

**Comment by Saransh-cpp** [comment]
Hi, @jhamman, this looks good to go now!

**Comment by jhamman** [comment]
Thanks @Saransh-cpp!

**Comment by joshmoore** [comment]
:heart:

**Pull request merged**
